### ISSUE TITLE
Plans for VSCode?

### ISSUE THREAD

**Issue by ggregoire** [dempfi/ayu#10]
Your theme is excellent, and specially the color scheme! VSCode is a great text editor but sadly there is a lack of good themes for ES6. Would be great to have yours on VSCode too. 😀

I saw the same question for Atom but I assumed that it's better for you to have separate issues for the different ports (in case you consider a VSCode port).

**Comment by dempfi** [comment]
thx @ggregoire :). if VSCode uses same format for themes as atom, it should be a easy to make port for both, however I haven't checked this yet.

**Comment by jsenjoy** [comment]
I like this theme, maybe I can try to implement one for VSCode. How about it? @dempfi

**Comment by MarvinAmador7** [comment]
+1 for a VS Code port, awesome work BTW

**Comment by jsenjoy** [comment]
I have already made a simple one: [vscode-ayu](https://marketplace.visualstudio.com/items?itemName=teabyii.ayu)

**Comment by ggregoire** [comment]
@jsenjoy It's great, thanks a lot!

**Comment by dempfi** [comment]
Version from @teabyii is really great and does everything I'd do.
