### ISSUE TITLE
Increase contrast of line numbers

### ISSUE THREAD

**Issue by JamieMason** [dempfi/ayu#100]
Thanks for this great theme @dempfi, it's been my go-to for a while now. 

One small problem I've been having is that I find the line numbers in the gutter too faint to read easily, is there some way I can edit the hex for those somewhere in my local installation please?

**Comment by dempfi** [comment]
Hey @JamieMason, you just need to edit [this line](https://github.com/dempfi/ayu/blob/master/ayu-light.tmTheme#L35) in `tmTheme` file of your preferred color scheme(mirage/light/dark). To edit ayu's files, use [this plugin](https://packagecontrol.io/packages/PackageResourceViewer).

**Comment by dempfi** [comment]
BTW, can you please tell what color scheme do you use?

**Comment by JamieMason** [comment]
Thanks a lot @dempfi, I'll try that in a moment. 

I'm using;

```
"color_scheme": "Packages/ayu/ayu-dark.tmTheme",
"theme": "ayu-dark.sublime-theme",
```

**Comment by JamieMason** [comment]
Thanks a lot for that, it's worked perfectly. I needed to switch to a different theme and then back for the changes to take effect (restarting sublime didn't seem to do it) but not the change is there 🍾
