### ISSUE TITLE
UI problem when I try to rename a file

### ISSUE THREAD

**Issue by AZLisme** [dempfi/ayu#101]
Hi I'm using ayu as my sublime theme and appreciated it.

Recently I find that when I try to add or rename a file, the filename input box is covered by the status bar, as the image blow shows:
![screenshot-ayu-input](https://cloud.githubusercontent.com/assets/8706522/23734945/75e3fa60-04bd-11e7-86ab-628b304b5cf9.png)

I wonder if this is my configuration problem or some thing else.

I'm using ST3 and the mirage theme, here is my Sublime User Setting:

```json
{
	"auto_complete_triggers":
	[
		{
			"characters": ".",
			"selector": "source.python"
		}
	],
	"color_scheme": "Packages/ayu/ayu-mirage.tmTheme",
	"font_size": 13,
	"ignored_packages":
	[
		"Vintage"
	],
	"theme": "ayu-mirage.sublime-theme",
	"ui_separator": false
}
```

Thank you very much 👍

**Comment by k15a** [comment]
#12

**Comment by AZLisme** [comment]
Fix by pulling up the panel, thx!
