### ISSUE TITLE
tiny popup text

### ISSUE THREAD

**Issue by deathaxe** [dempfi/ayu#102]
The text displayed in popups is very small and does not scale with the font-size setting.

The reason is the definition of a fixed font size of 12px in the popup stylesheet.

You should not add a font-size at all in order to let ST scale the popup text with the normal `font_size` setting.

**Comment by dempfi** [comment]
fixed in https://github.com/dempfi/ayu/releases/tag/3.0.0

**Comment by deathaxe** [comment]
Nice to see.
