### ISSUE TITLE
GitGutter colors

### ISSUE THREAD

**Issue by deathaxe** [dempfi/ayu#103]
All ayu color schemes define the same color for `markup.changed.git_gutter` and `markup.deleted.git_gutter` scopes.

Therefore changed and deleted regions can't be distinguished in the minimap.
Same issue exists with simplified gutter icons (e.g. bars).

#### Recommendation:

- highlight `markup.deleted.git_gutter` with a red like color.
- highlight `markup.changed.git_gutter` with a yellow like color.
- highlight `markup.inserted.git_gutter` with a green like color.
- highlight `markup.ignored.git_gutter` with a grey like color.
- highlight `markup.untracked.git_gutter` with a grey like color.

#### Example: _ayu mirage.tmTheme_
```xml
		<dict>
			<key>name</key>
			<string>GitGutter inserted</string>
			<key>scope</key>
			<string>markup.inserted.git_gutter</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#BAE67E</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>GitGutter changed</string>
			<key>scope</key>
			<string>markup.changed.git_gutter</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#FFD580</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>GitGutter Deleted</string>
			<key>scope</key>
			<string>markup.deleted.git_gutter</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#EE1010</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>GitGutter Ignored</string>
			<key>scope</key>
			<string>markup.ignored.git_gutter</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#5C6773</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>GitGutter Untracked</string>
			<key>scope</key>
			<string>markup.untracked.git_gutter</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#5C6773</string>
			</dict>
		</dict>
```

**Comment by dempfi** [comment]
@deathaxe this is done in https://github.com/dempfi/ayu/releases/tag/3.1.0

**Comment by piccombs** [comment]
Are `markup.changed.git_gutter` and `markup.inserted.git_gutter` supposed to display the same blue color?
