### ISSUE TITLE
Wrong folder expanded in sidebar when using Mirage2

### ISSUE THREAD

**Issue by BridgeTheGap** [dempfi/ayu#104]
When using Mirage 2 theme, the folder above is expanded when you click `>` next to the folder name in the sidebar.
Collapsing the list works fine though.

**Comment by k15a** [comment]
The mirage 2 theme is only for sublime 2. You're probably using sublime 3 and should switch to the  normal mirage theme.

**Comment by BridgeTheGap** [comment]
It would be nice if `mirage` was also customizable like mirage 2. (Tab size, height, etc.)
