### ISSUE TITLE
Weird Bar fonts

### ISSUE THREAD

**Issue by Mrprofessor** [dempfi/ayu#105]
Bar fonts are different in windows

![Image of Yaktocat](https://mrprofessor.github.io/md5encrypter/Capture.PNG)

Watch the bar..working fine in Linux though.

**Comment by k15a** [comment]
Add `"ui_fix_tab_labels": true` to your config.

**Comment by Mrprofessor** [comment]
Already did that.But how to change the font?

**Comment by k15a** [comment]
Do you have sublime 2 or 3?

**Comment by Mrprofessor** [comment]
3

**Comment by k15a** [comment]
`"font_face": "Roboto Mono"` is the options you're probably looking for.

**Comment by Mrprofessor** [comment]
It only changes the editor font not the font of the bar.
