### ISSUE TITLE
Change ui font

### ISSUE THREAD

**Issue by Mrprofessor** [dempfi/ayu#107]
How to change the default "Source Code Pro" font ??

``` json
"ui_font_source_code_pro": true, // use [Source Code Pro](https://fonts.google.com/specimen/Source+Code+Pro) for UI
```

**Comment by dempfi** [comment]
First, install font from the [lint](https://fonts.google.com/specimen/Source+Code+Pro). Second, put ```"ui_font_source_code_pro": true``` in your editor config.
