### ISSUE TITLE
File Link Colors

### ISSUE THREAD

**Issue by findborg** [dempfi/ayu#11]
I have to say I love the colors for the code side.  However,  sidebar and tab links are real hard to read.  How can I edit them to lighten them up more against the background?
Note that the hover and active "white"  is great and easy to read.

**Comment by dempfi** [comment]
Hey @findborg, I'm about to release an update in few days with fixes for ST2 and color contrast.

**Comment by findborg** [comment]
Oh OK,  perfect and I must say you are doing a good job on this.

**Comment by dempfi** [comment]
Thanks @findborg, a few days became a couple of hours 😀

**Comment by findborg** [comment]
Ok will do.  I  will reply with opinion after seeing.
