### ISSUE TITLE
why the icons is not work well?

### ISSUE THREAD

**Issue by PPPHUANG** [dempfi/ayu#110]
why the icons is not work well?

**Comment by k15a** [comment]
What do you mean?

**Comment by PPPHUANG** [comment]
Do not show the icons of the file type

**Comment by dempfi** [comment]
Hi @PPPHUANG, I'm sure I know what you mean, but from the next release file icons will be removed from the package and handler by third party packages. So, I will not fix anything in current versions related to file icons.

**Comment by PPPHUANG** [comment]
Thank you, I have solved this problem, probably because the 3038 version of the sublime is not compatible, replaced by 3083 just fine
