### ISSUE TITLE
Build 3128 sidebar font size issue

### ISSUE THREAD

**Issue by jano23** [dempfi/ayu#111]
Today's update to 3128 left the sidebar font very small.
Tried removing and installing the package again.

**Comment by dempfi** [comment]
Hi @jano23, can you please add some information about OS and display's DPI?

**Comment by jano23** [comment]
Sure. Should have included that on my original post.

Windows 10 - 3840x2160 and it was working fine before updating to 3128

**Comment by jano23** [comment]
@dempfi - looks like build 3131 has fixed the problem -

**Comment by dempfi** [comment]
@jano23 I see, you may want to use the theme from this PR https://github.com/dempfi/ayu/pull/113. The PR is still in development but it's more or less stable and I'd really appreciate any bugreports about that version of ayu on dev Sublime in Windows machine.

**Comment by dempfi** [comment]
This issue should be fixed with release https://github.com/dempfi/ayu/releases/tag/3.0.0
