### ISSUE TITLE
title_bar support

### ISSUE THREAD

**Issue by el** [dempfi/ayu#112]
As of [Build 3127](http://www.sublimetext.com/3dev) ST now supports colors for title bars

here is for dark theme:

```
  {
    "class": "title_bar",
    "fg": [242, 151, 24],
    "bg": [15, 20, 25]
  },
```
![screen shot 2017-04-13 at 21 40 51](https://cloud.githubusercontent.com/assets/1488164/25019051/ee0c7a9a-2091-11e7-87f0-2589a70f16b6.png)

**Comment by dempfi** [comment]
Hi @el. Thx for pointing out. I just started playing with new dev builds and will release new version of ayu using all the cool features of new ST builds once they will be in stable builds.

**Comment by sebastianks** [comment]
@el Where do you add this for the dark title bar?

**Comment by maticrivo** [comment]
@dempfi do you have a branch we can play with for now? for people who use the ST dev builds..

**Comment by maticrivo** [comment]
@dempfi just one thing, i don't see the file icons when using the `build-3127-improvements` branch

**Comment by elbrinke** [comment]
Hello, 

How can I test this out?
 {
    "class": "title_bar",
    "fg": [242, 151, 24],
    "bg": [15, 20, 25]
  },

As mentioned above?

**Comment by dempfi** [comment]
@maticrivo yep, ayu will no longer provide file icons but instead will use A File Icon plugin. Unfortunately manually installed version of ayu can not automatically download that plugin, but you can just install it by your own.

**Comment by dempfi** [comment]
@elbrinke you better install ayu from this branch https://github.com/dempfi/ayu/tree/build-3127-improvements as described here https://github.com/dempfi/ayu/tree/build-3127-improvements#manual-installation. That branch is almost ready for release, I just need to wait for the next stable release of ST3

**Comment by victorronnow** [comment]
Any updates on this since build 3143 is now released?

**Comment by dempfi** [comment]
Released in https://github.com/dempfi/ayu/releases/tag/3.0.0.

**Comment by maticrivo** [comment]
@dempfi is the new release installable with Package Manager?
