### ISSUE TITLE
tab bar font Blur？

### ISSUE THREAD

**Issue by bestvow** [dempfi/ayu#114]
see pic
what should i do for fix it?(And thx nice theme!)
![20170424224755](https://cloud.githubusercontent.com/assets/24888709/25342955/3028751c-2940-11e7-95b0-690204979b4f.png)

**Comment by k15a** [comment]
Readme:
```JSON
"ui_fix_tab_labels":        true, // to fix tab labels if they look not right
```

**Comment by bestvow** [comment]
Got it ! I need read option more careful 。
