### ISSUE TITLE
?

### ISSUE THREAD

**Issue by phatvip123** [dempfi/ayu#116]
![capture](https://cloud.githubusercontent.com/assets/15698245/25777264/2046c650-3302-11e7-944e-55cb68e7a09b.PNG)

**Comment by justinwzig** [comment]
Common problem with ayu and other themes. If you go to your preferences (preferences in title bar\settings) and add `"ui_fix_tab_labels": true,` underneath everything but inside the brackets it should fix it. Your settings file should look like this: 
![image](https://cloud.githubusercontent.com/assets/4504400/25777300/dc7326fc-329e-11e7-9e29-535f128a945e.png)

**Comment by deathaxe** [comment]
I wouldn't call it a common problem. AYU uses the shadow color to render text and the foreground color to render the shadow. This is something the font anti aliasing algorithms seem to struggle with. I didn't yet see any other theme handling colors like that.

**Comment by justinwzig** [comment]
Alright, my bad. It just seems to happen to me on every variety of pc I install st3/ayu on so I figured it must be a thing. Either way, that setting should fix it right up.

**Comment by deathaxe** [comment]
Yes, it just exchanges forground and shadow colors as being used by any other theme on any machine.
