### ISSUE TITLE
Tab File name problem

### ISSUE THREAD

**Issue by Mxater** [dempfi/ayu#117]
In the tab bar, the names of the files are displayed in a strange way, which prevents them from seeing the names correctly.

![2017-05-17 17_32_22-untitled - sublime text](https://cloud.githubusercontent.com/assets/4630666/26177246/e2931ae8-3b26-11e7-8ae4-a7f5e5cc7caf.png)

**Comment by dempfi** [comment]
Please, read readme before submitting your "bug"
```
"ui_fix_tab_labels":        true, // to fix tab labels if they look not right
```
