### ISSUE TITLE
JSON snippets in to README file

### ISSUE THREAD

**Issue by gabsprates** [dempfi/ayu#120]
I'd opened this Issue because of this:

![screenshot](https://cloud.githubusercontent.com/assets/12635603/26635555/8322d40c-45f0-11e7-8387-1f23356f4ce6.png)

Markdown snippets syntax are breaked in Package Control.

I don't know if Package Control accepts ` ```json ` snippet, but **if so**, i suggest you put a new line (`\n`) before of it, e.g.:

Currently:

```
For light theme:
```json
"theme": "ayu-light.sublime-theme",
"color_scheme": "Packages/ayu/ayu-light.tmTheme",
```

How i think you can fix it:

```
For light theme:

```json
"theme": "ayu-light.sublime-theme",
"color_scheme": "Packages/ayu/ayu-light.tmTheme",
```

But **if don't**, you could change to just ` ``` `, with out *json*?

**Comment by dempfi** [comment]
fixed :), thx @gabsprates
