### ISSUE TITLE
Contrast for the text is very low in workbench using dark theme

### ISSUE THREAD

**Issue by teabyii** [dempfi/ayu#124]
![image](https://user-images.githubusercontent.com/4496552/27482692-00aebe9c-5855-11e7-9e15-60d48c988ad2.png)

https://github.com/teabyii/vscode-ayu/issues/11

**Comment by dempfi** [comment]
Hear you @teabyii. Will fix it soon.

**Comment by dempfi** [comment]
@teabyii Fixed in 2.2.1, check out this commit https://github.com/dempfi/ayu/commit/30f680412d186a777ffe009c1de1b5fa28b71c08
