### ISSUE TITLE
No borders visible

### ISSUE THREAD

**Issue by straku** [dempfi/ayu#125]
Hi, after installing skin I seem to have a problem with borders - none of them are visible. Example screenshot:
<img width="1263" alt="zrzut ekranu 2017-07-08 o 12 56 57" src="https://user-images.githubusercontent.com/8038404/27984716-111595e2-63dd-11e7-9924-5f7897c70330.png">
Ayu is the only package installed, I didn't apply any custom settings / styles.
Any idea what could be causing that?

**Comment by dempfi** [comment]
Hi @straku, you need to enable them in your config. Just add `"ui_separator": true`

**Comment by straku** [comment]
Thank you very much and sorry for what now seems a very stupid question 😅
