### ISSUE TITLE
Default UI Font

### ISSUE THREAD

**Issue by desislavsd** [dempfi/ayu#127]
Themes are awesome! Great work!

Can you please add an option to use the default Font for UI in Sublime even though I have Roboto installed, since I personally and probably someone else find it more readable. 

Thanks in advance!

**Comment by dayfuaim** [comment]
Yes. I'd like to have this too. :)
With Roboto Mono, I see tabs like this:
![2017-07-13 17-00-22](https://user-images.githubusercontent.com/1274699/28170084-e68b0d70-67ec-11e7-8e40-2281b9a04044.png)

**Comment by ticky** [comment]
I’ve got a patch (#128) which would add a `ui_font_default` setting, which would set the “default” font (as in whatever Sublime Text considers the base, not the monospace fallback normally used).

**Comment by desislavsd** [comment]
Looks great! Hope @dempfi will merge it!
