### ISSUE TITLE
Highlight active tab with different background color

### ISSUE THREAD

**Issue by Gal3riel** [dempfi/ayu#132]
Hi, dear author,
I am using light theme mixed with a dark color theme; in this setting, the one pixel line orange color is not so obvious to catch. I am wondering if it is possible to add an option to highlight the active tab with a different background color.

**Comment by ababich** [comment]
Hi! I'm using light `Ayu Light` theme and has no any visual separation of active tab at all

Except small `X` visible only for current tab. This is extremely inconvenient. Please, give a hint how to fix this

**Comment by dempfi** [comment]
Hi guys, will work on this in next minor version.

**Comment by dempfi** [comment]
@Gal3riel, @ababich please check version 5, I've improved quite a lot on that regards. Sorry it took sooo long.
