### ISSUE TITLE
Italicize comments and attributes

### ISSUE THREAD

**Issue by mattJamesMedia** [dempfi/ayu#133]
I love this theme and can only imagine how sweet it would be if it supported Operator Mono's italicized comments and attributes similar to Oceanic Next.

**Comment by k15a** [comment]
This is related to: https://github.com/dempfi/ayu/issues/67

**Comment by dempfi** [comment]
Hi @mattJamesMedia, comments are italic now, haven't decided about attributes. Anyhoo, will take another look at syntax highlighting today/tomorrow. I'll close this issue, but if you think there is something else, feel free to reopen.

**Comment by mattJamesMedia** [comment]
Hey there, super psyched about this. Reinstalling in VS Code and reloading, I don't have italicized comments. Am I missing something? Thanks for your work!

**Comment by k15a** [comment]
This repo is about the sublime theme not the one for VSCode.

**Comment by mattJamesMedia** [comment]
Apologies for the oversight.
