### ISSUE TITLE
Tab's font color

### ISSUE THREAD

**Issue by imilo** [dempfi/ayu#135]
I've got a bug with tab's font color. Example:

![tabs](https://user-images.githubusercontent.com/8048912/29837707-946e35a0-8d01-11e7-8f3b-375f81c9b6ac.png)

As you see - looks like letters are light with dark shadow. Is this a bug or I have a misconfiguration somewhere? Both UI Theme and Color Theme are **ayu**, and other themes look properly

**Comment by imilo** [comment]
Thanks!

**Comment by dempfi** [comment]
@imilo this should be fixed in latest version of ST3
