### ISSUE TITLE
New Sublime 3.0 update changed all the Sidebar, Header, and Status Bar fonts

### ISSUE THREAD

**Issue by pirate** [dempfi/ayu#137]
I much prefer the old fonts from the Ayu theme, but it looks like the new update changed them to some less-than-pretty monospace font.

Is there any way to change it back?

<img width="232" alt="screen shot 2017-09-13 at 1 51 31 pm" src="https://user-images.githubusercontent.com/511499/30395090-b1a04994-988a-11e7-8e77-33c39aaa2af6.PNG">
<img width="177" alt="screen shot 2017-09-13 at 1 51 24 pm" src="https://user-images.githubusercontent.com/511499/30395089-b19aa660-988a-11e7-81f2-25fd2ea4771a.PNG">

Opening `ayu-dark.sublime-theme` and removing every line with `"font.face": ...` worked to fix it:
```json
  {
    "class": "sidebar_heading",
    "settings": ["ui_font_default"],
    "font.face": "Roboto Mono"   <- removed all
  },
```

**Comment by dempfi** [comment]
Hi @pirate there is an option for this `ui_font_default` :)

**Comment by dempfi** [comment]
@pirate ayu by default uses Roboto Mono and if it's not installed then sublime picks some fallback monospaced font which might look not that great. I'll probably ditch roboto mono and use default font by default in next releases since default font in ST3 is great.
