### ISSUE TITLE
Missing file type icons

### ISSUE THREAD

**Issue by jhermsmeier** [dempfi/ayu#138]
With the latest update the file type icons have changed to generic `<>` icons (instead of the bundled ones) – is this intentional? I also saw https://github.com/dempfi/ayu/issues/110, which states that icons will be handled by third-party packages – is that the case now (or did that never happen)?

Sublime v3.0, Build 3143 (same behavior with the 3142 dev build):

![screen shot 2017-09-14 at 12 40 13](https://user-images.githubusercontent.com/244907/30425587-f0abfaba-9949-11e7-88ca-760fd786b5d7.png)

**Comment by dnmarques** [comment]
I also had this problem. As icons are now handled by third-party packages, I installed this package https://github.com/ihodev/a-file-icon and it solved the problem. I did not do a big research of the best package for icons.

**Comment by jhermsmeier** [comment]
Sweet, using the same now, thanks!

**Comment by beaniemonk** [comment]
@dnmarques thanks!

As far as I can tell, Ayu now ships with the same icons as 'A File Icon' anyway. And Ayu looks like it has added theme support for 'A File Icon', I just think it isn't explicitly stated (yet) that you need to manually install it as a dependency.

For me personally, the new icons are a little big and distracting. But 'Preferences->Package Settings->A File Icon' brings up some helpful options to tone them down a bit to be more like the old icons. I ended up settling on this:

```json
{
  "opacity": 0.75,
  "opacity_on_hover": 0.75,
  "opacity_on_select": 1.0,
  "size": 6,
  "force_mode": true
}
```

**Comment by dempfi** [comment]
@beaniemonk is correct, ayu now ships with support for A File Icon package and relies on it.
