### ISSUE TITLE
Disable title bar modifications & title bar bug

### ISSUE THREAD

**Issue by Flerex** [dempfi/ayu#139]
I'd be great if we had an option to disable the new design of the macOS title bar. I'm not a big fan of apps that modify the original design of the OS and this change kinda annoyed me.

On the other hand, I'd like to report a bug with this very same feature. Apparently, there's some kind of weird behavior with the title in the title bar. See:

![screen shot 2017-09-14 at 14 18 13](https://user-images.githubusercontent.com/3910120/30429426-a9f9ef2e-9957-11e7-8a58-a0c35eb59026.png)

**Comment by mrunc** [comment]
I just noticed the ugly file icon in title bar after upgrading, was this there before?
how can I disable just the only the file icon for now?

**Comment by dempfi** [comment]
Hi @Flerex, I’ll add such option in next release.

@mrunc AFAIK, file icon shown in the titlebar is the icon associated with the file type in macOS level and has nothing to do with sublime itself

**Comment by dempfi** [comment]
@Flerex released minor updated with option `ui_native_titlebar` to use native titlebar style

**Comment by Flerex** [comment]
@dempfi thank you very much! I appreciate it :)
