### ISSUE TITLE
Sidebar File icons disappeared after build 3134

### ISSUE THREAD

**Issue by ovheurdrive** [dempfi/ayu#141]
Today, my sublime Text 3 on Linux updated to build 3134, and the file icons on the sidebar were all replaced by "< >" icons. I'm using ayu-dark with the following preferences : 
```
{
	"color_scheme": "Packages/ayu/ayu-dark.tmTheme",
	"font_size": 10,
	"ignored_packages":
	[
		"Vintage"
	],
	"theme": "ayu-dark.sublime-theme",
	"ui_big_tabs": true,
	"ui_fix_tab_labels": true,
	"ui_font_source_code_pro": true,
	"ui_separator": true,
	"ui_sidebar_highlight_row": true,
	"ui_wide_scrollbars": true
}
```
Here is what it looks like now : 

![image](https://user-images.githubusercontent.com/24658300/30461039-3c26c2d6-99fe-11e7-907c-2c9cc0edfe99.png)

**Comment by dempfi** [comment]
Hi 👋, starting from version 3 ayu uses A File Icon package to configure icons. Just install it from here https://github.com/ihodev/a-file-icon and you’ll get icons back :)

**Comment by sobolevn** [comment]
@dempfi Any chance to get the old icons back? What are the options to configure?

**Comment by ihodev** [comment]
@dempfi There is no need to add all icons from `A File Icon` you can left your original ones and plugin will add only missing icons.

**Comment by dempfi** [comment]
@sobolevn yes, will take care of it in next release

Thank you very much @ihodev for A File Icon and advise. I'll remove icons of A File Icon and leave only originals. BTW, are there a way to control size of icons from the theme?

**Comment by ihodev** [comment]
I'll add `.a-file-icon-rc` starting the next version, you'll be able to set defaults for all `A File Icon` setting on per theme basis.

**Comment by ihodev** [comment]
I'll write when it will be ready or make a PR :wink:

**Comment by dempfi** [comment]
that would be a great addition 👍
