### ISSUE TITLE
Cannot change title bar colour

### ISSUE THREAD

**Issue by jinoantony** [dempfi/ayu#143]
Im using ayu mirage theme but the color of title bar is always white.
![screenshot 56](https://user-images.githubusercontent.com/21086824/30468812-e34e7098-9a0a-11e7-9d14-a1a3c38cc7cf.png)

**Comment by ihodev** [comment]
@jinoantony Currently Sublime Text doesn't support that on Windows & Linux.

**Comment by kklot** [comment]
It happens now in Mac OS Mojave, the title bar is white 😢, can you check?
