### ISSUE TITLE
Highlight entity.name

### ISSUE THREAD

**Issue by deathaxe** [dempfi/ayu#144]
The color scheme currently provides `entity.name.function` and `entity.name.tag`. The recent releases of ST and PackageDev include several other `entity.name. ...` scopes which keep uncolored.

Would you therefore please follow the suggestions in the _Minimal Scope Coverage_ paragraph of https://www.sublimetext.com/docs/3/scope_naming.html and add `entity.name` to have them highlighted correctly.

I'd be very fine with them being highlighted with the same color `entity.name.tag` are.

Thanks in advance.

**Comment by dempfi** [comment]
Hey @deathaxe, I already started working on colors update here https://github.com/dempfi/ayu/pull/145

**Comment by deathaxe** [comment]
Oh, cool. Why did I miss that? 🤔  Will check it out. Thank's much!

**Comment by dempfi** [comment]
@deathaxe because I opened PR after you opened this issue 🙃

**Comment by deathaxe** [comment]
Why did you dismiss the annotations stuff?

I pulled your PR yesterday and python annotations were scoped light red. Now its gone.

```python
@contextmanager   <- annotation
def function
   ...
```

**Comment by deathaxe** [comment]
Ah just see:

```python
class FilteringImportHook:
    """PEP-302 importer that delegates loading of modules to a function."""

    def __init__(self, condition, load_module):
        super().__init__()
        self.condition = condition
        self.load_module = load_module

    @classmethod <- This is support.functions
    def when(cls, condition):
        """A handy loader function decorator."""
        return lambda load_module: cls(condition, load_module)
```

**Comment by dempfi** [comment]
@deathaxe I'll open additional PR to resolve few leftover issues including user-defined decorators

**Comment by deathaxe** [comment]
Cool. The changes look well so far. I especially like the constant scoping of punctuations and parentheses now.
