### ISSUE TITLE
How to restore normal font, not italic?

### ISSUE THREAD

**Issue by GenaANTG** [dempfi/ayu#146]
Italic font is terrible in use.

**Comment by dempfi** [comment]
Hi @GenaANTG, I might have overused italic in latest update, will take care of it. But can you please explain why do you think it's terrible in use?

**Comment by GenaANTG** [comment]
I think best approach is regular monospace font with good contrasts colors.
Your themes for sublime are perfect!

**Comment by dempfi** [comment]
thx @GenaANTG, much appreciated 😊

**Comment by Phestek** [comment]
What about making extensive italic use optional (by making an option in config for it)? I liked italics a lot.

**Comment by dempfi** [comment]
@Phestek For now I actually disabled italics only in places where they didn't add much value. Can you check version 3.1.1?

and yes, I'll look into some settings option — this sounds like a good resolution for this issue

**Comment by Phestek** [comment]
I'm using Sublime for C++ and Assembly only, so the only italicized things I see are comments. Having 'class', 'struct' and 'enum' italicized was nice.

**Comment by dempfi** [comment]
@Phestek Got it 👍, will release some solution soon

**Comment by meduzen** [comment]
(My 2 cents just below.)

I switched my theme back to Brogrammer, awaiting for a fix. I’m just writing SCSS right now, and I really can’t stand the italic apart from comments. I guess it’s really personal taste, so a setting will indeed be a good thing.

By the way, the work done since 3.0 (and even before) is really awesome. Ayu Light & Mirage are my favorite themes. I switch between both depending on surrounding light. So, thank you.

**Comment by dempfi** [comment]
@meduzen thx for kind words 😊. And yeah, italic properties in css-like languages was a major fuck-up. I fixed it in https://github.com/dempfi/ayu/releases/tag/3.1.4. Can you please check it out?

**Comment by meduzen** [comment]
Thanks for your quick answer! Yep, it’s back to normal in CSS. I gave a quick check at some JS & PHP files, some words are in italic, more like some constant (like `window` in JavaScript, or classes names in PHP like in `Route::myMethod()` or like in `use Illuminate\Http\Request;`). I should have check before, sorry. :/

At this point, I guess it’s really personal choice. As you are the main contributor of this theme, if you think that these JS/PHP terms should stay Italic, I’ll understand. As it comes to themes, creator must have the final word. Then maybe I’ll fork it or write a pull request for a non-italic version. What do you think is the best for people wanting non-italic at apart from comment?

**Comment by GenaANTG** [comment]
@dempfi Thank you!

**Comment by dempfi** [comment]
@meduzen right now only types and some language constants are in italic. For now I think you can fork ayu and remove all italics while I'm figuring out best possible solution for some configuration.

**Comment by meduzen** [comment]
Perfect! Before forking, I’ll try to stick with it this week in order to make a definitive opinion on this _italic vibe feeling_.

**Comment by dempfi** [comment]
@meduzen one week passed 😉, what do you think about a bit of italic fonts?

**Comment by meduzen** [comment]
Hi @dempfi !

I’m still sticking a lot to CSS in my current project, so I can’t tell for JS/PHP yet. But for the few CSS keywords using italic (like `auto`, `none`,  `hidden`, `relative`), I’m completely fine with italic as they are a minority in the code. :)

I will probably have a stronger opinion on italic around on late October. Thanks for the reminder!

**Comment by Keith94** [comment]
I also don't like the use of italic fonts, when editing css it looks out of place.

![image](https://user-images.githubusercontent.com/5490615/31567964-df1e55e2-b026-11e7-94e1-2466fdbe5ab3.png)

**Comment by meduzen** [comment]
More feedback, as some weeks have passed, during which I wrote mainly PHP, JS, CSS and HTML: I’m perfectly fine with italic. And as I’m now used to it, I can say italic sometimes helps me to detect a typo before my linter does. :)

**Comment by Ralvke** [comment]
For global disable italic fonts you can use `"font_options": ["no_italic"]` in settings
https://forum.sublimetext.com/t/removing-font-styles-in-syntax/3795/4

**Comment by dempfi** [comment]
Thx @Ralvke, your solutions is clean and ideal for everybody. 

Closing the issue.
