### ISSUE TITLE
File icons are overridden by A File Icon 

### ISSUE THREAD

**Issue by idiotWu** [dempfi/ayu#147]
| Environment | Version |
|:-------|:---------|
| System | macOS 10.12.6 |
| Sublime Text | 3.0, Build 3143 |
| **ayu** | **v3.1.1** |
| A File Icon | v3.2.1 |
| **Activated Theme** | **ayu-mirage** |

File icons seem to be overridden by A File Icon package:

#### Icons found in `ayu/icons`:
![cpp](https://user-images.githubusercontent.com/6022672/30523033-bfa740a0-9c14-11e7-8a55-3e1c6e64a7b7.png) ![shell](https://user-images.githubusercontent.com/6022672/30523040-de20c272-9c14-11e7-882f-a7a5e347aa5b.png)

#### Icons seen on sidebar:
![image](https://user-images.githubusercontent.com/6022672/30523065-7cf71c66-9c15-11e7-93d6-a4e7cc49712d.png)

**Comment by dempfi** [comment]
Hi @idiotWu, sorry for inconsistency. Fixed this issue in https://github.com/dempfi/ayu/releases/tag/3.1.2. There will be additional tuning to file icons keep tuned :)

**Comment by idiotWu** [comment]
@dempfi thanks for the quick fix! 

Um...one more thing. I think you just posted a wrong screenshot of "Mirage with ui_separator option off" in readme, it appears to be a screenshot of `"ui_separator": true` 🙈.

**Comment by dempfi** [comment]
oh my 🤦‍♂️, thx for mentioning that
