### ISSUE TITLE
Ayu Dark no longer highlight variables inside string (PHP) after update Sublime Text

### ISSUE THREAD

**Issue by anovsiradj** [dempfi/ayu#148]
from what I remember, ayu dark always highlight variables written inside string on PHP.
```php
$q = $db->query("SELECT * FROM tbl WHERE a = '{$var1}' AND b = '{$var2['key']}' ")
```

before update to newest (stable) sublime text, `$var1` always colored, but after update it's longer colored (except `$var2['key']` - only `['key']` part is highlighted)

![ayu dark problem cropped - screenshot from 2017-09-18 14-11-15](https://user-images.githubusercontent.com/6737021/30531939-91ae8750-9c7b-11e7-84b2-cd95b59e72cd.png)

*sory for my english*
thanks.

**Comment by dempfi** [comment]
Hey @anovsiradj, sorry for inconvenience. Will fix it soon.

**Comment by dempfi** [comment]
fixed in https://github.com/dempfi/ayu/releases/tag/3.1.3
