### ISSUE TITLE
Wrong appearance in sidebar

### ISSUE THREAD

**Issue by Keith94** [dempfi/ayu#149]
In the latest update the tab backgrounds don't fill the whole width of the sidebar like it used to. Is there a way to fix that and possibly move the close button to the right side of the tab? How it looks:

![image](https://user-images.githubusercontent.com/5490615/30532812-0f91df12-9c0b-11e7-9f87-44d24ad9ebb2.png)

**Comment by dempfi** [comment]
hey @Keith94, sorry for inconvenience will fix it as soon as I can

**Comment by dempfi** [comment]
fixed in https://github.com/dempfi/ayu/releases/tag/3.1.6
