### ISSUE TITLE
Srollbar width?

### ISSUE THREAD

**Issue by nlg** [dempfi/ayu#15]
Hi, I like your theme but the width of the scrollbar is waaaaay to small. How can I increase it?

**Comment by dempfi** [comment]
Hey @nlg, I, glad you like it. I thought no one is using scrollbars :)

so anyway here the solution:
1. Install https://packagecontrol.io/packages/PackageResourceViewer
2. Open `ayu` ui theme file(`ayu.sublime-theme` or `aye-light.sublime-theme`)
3. Change `1` to `2...` in `"content_margin": [1, 12]` at line `888` to get wider vertical scrollbar
4. Change `1` to `2...` in `"content_margin": [12, 1]` at line `900` to get wider horizontal scrollbar

**Comment by nlg** [comment]
Nice thanks, 5 was an OK value :)

**Comment by lommes** [comment]
Since this will be overwritten by updates I think it would be very nice if this was configurable in any way. Working on a laptop, an average PHP project always has a structure were scrolling in the tree is necessary

**Comment by mxm145** [comment]
I can't find the file ayu.sublime-theme, where is it?
