### ISSUE TITLE
Ruby instance variables not highlighted?

### ISSUE THREAD

**Issue by chrismanderson** [dempfi/ayu#150]
I could swear this has just started happening, but I don't know for sure. I'm see Ruby instance variables appear as just white and not with any special highlighting, which I feel like they should have. E.g. in this example `@gift_card` should have a different color.

![](https://cl.ly/1c0T3a2A2u3N/Image%202017-09-18%20at%2010.52.19%20AM.png)

**Comment by dempfi** [comment]
hey @chrismanderson, this seems like a regression. will take a look today

**Comment by dempfi** [comment]
fixed in https://github.com/dempfi/ayu/releases/tag/3.1.5 :)

**Comment by chrismanderson** [comment]
3 hours from bug report to fix. Outstanding!! 🎉 🎉
