### ISSUE TITLE
Weird tab background

### ISSUE THREAD

**Issue by Flerex** [dempfi/ayu#151]
It happened since the last update. It only happens in the dark theme.
![screen shot 2017-09-18 at 17 19 19](https://user-images.githubusercontent.com/3910120/30549649-9a55cba6-9c95-11e7-8951-2638b5e8b406.png)

**Comment by dempfi** [comment]
this is strange... @Flerex what version of sublime do you use? Also, what version of macOs?

**Comment by respinos** [comment]
I see something similar in the sidebar: 2.0.2 build 2221
![image](https://user-images.githubusercontent.com/537867/30552809-46601eca-9c6d-11e7-9ec1-67be5b4a4caa.png)

**Comment by Flerex** [comment]
I'm using macOS High Sierra and Sublime Text 3142.

**Comment by dempfi** [comment]
I can't reproduce this issue in ST3, looking into the issue in ST2

**Comment by Flerex** [comment]
It seems it got fixed in the last update. Thanks!
