### ISSUE TITLE
separator between title bar and editor area

### ISSUE THREAD

**Issue by jemhuntr** [dempfi/ayu#152]
![](https://i.imgur.com/dDZbyHw.png)

With the recent stable release of the color-able title bars, the vertical strokes with `ui_separator` on look like they're going up leading nowhere. It would look much much more seamless if there was a separator right below the title bar which separates it visually from everything else.

Problem is, I don't know if this is possible with Sublime yet.

Bonus: See the additional horizontal separator on the status bar. Would be a nice addition as well (at least personally, I think it looks better with a stroke there).

**Comment by dempfi** [comment]
@jemhuntr I would love to have separator between titlebar and rest of the window, but there no way to achieve this with current API. But I might have a hacky solution 🙃 will try it out.

**Comment by jemhuntr** [comment]
Haha alright, that's great! Will stay tunes for that option :)

**Comment by dempfi** [comment]
@jemhuntr titlebar separators are released in https://github.com/dempfi/ayu/releases/tag/3.1.8. I promise to think on status bar separators

**Comment by jemhuntr** [comment]
Nice, thanks!!
