### ISSUE TITLE
restore previous color scheme for markdown

### ISSUE THREAD

**Issue by worm929** [dempfi/ayu#153]
I appreciate all the latest work on the theme, but I was really used to the color scheme of Markdown GFM, and had incorporated it into my workflow... but the last update changed everything, I don't recognize my own files anymore. 

Is it possible for me to grab a backup of the old version and replace it?

**Comment by dempfi** [comment]
Hi @worm929, is it because everything is white or because colors are different? Does this look OK for you?

<img width="724" alt="screen shot 2017-09-19 at 9 12 29 pm" src="https://user-images.githubusercontent.com/4568573/30607899-52e9e820-9d7f-11e7-8e81-f347d04d3cff.png">

**Comment by worm929** [comment]
Yes, I think it's mostly because it's all white, now that you bring it up.

I also really used the fact that titles become all orange, so I could do really long strings of "#" as a sort of visual delimiter. But now not only the text is not orange, if I go past 6 continuous # it defaults to white:
![image](https://user-images.githubusercontent.com/1861891/30617403-4da4a476-9d6c-11e7-84d9-8a9265732bd9.png)

Here is how I see the same text you pasted:
![asd](https://user-images.githubusercontent.com/1861891/30617311-d1bebf86-9d6b-11e7-9051-53633b13d5fd.png)

_Using Sublime Text 3.0 Build 3143 - Unregistered_

**Comment by dempfi** [comment]
Fixed in https://github.com/dempfi/ayu/releases/tag/3.2.1

**Comment by worm929** [comment]
awesome! I just got the update and it works.
thank you so much
