### ISSUE TITLE
Add support for PackageDev's settings completions/tooltips/linting

### ISSUE THREAD

**Issue by deathaxe** [dempfi/ayu#154]
Could you add support for PackageDev's settings tooltips/completions/linter, please?

This can be done by adding a Preferences.sublime-settings file with all settings provided by this package with a small description above.

This enables PackageDev package to:

 - provide completions of the settings keys
 - display a tooltip with the comment as description
 - mark the settings as valid by the internal linter

The linter underlines all unknown settings, which are not part of at least on packages Preferences.sublime-settings file.

### Example
```
{
    // AYU - Theme: Use native titlebars on macOs
    "ui_native_titlebar": false,

    // AYU - Theme: Show separators between panels
    "ui_separator": false,

    // AYU - Theme: Use smaller font size for UI
    "ui_font_size_small": false,

    // AYU - Theme: Increased tab height
    "ui_big_tabs": false,

    // AYU - Theme: Fix ugly looking tab labels
    "ui_fix_tab_labels": false,

    // AYU - Theme: Use Source Code Pro as UI font
    "ui_font_source_code_pro": false,

    // AYU - Theme: Use Sublime's default UI font
    "ui_font_default": false,

    // AYU - Theme: Display wider scrollbars
    "ui_wide_scrollbars": false
}
```

**Comment by dempfi** [comment]
good catch @deathaxe, will add it soon 👍

**Comment by dempfi** [comment]
Done in 4.0.0.
