### ISSUE TITLE
ayu theme for Hyper terminal?

### ISSUE THREAD

**Issue by victorronnow** [dempfi/ayu#155]
I would love to see ayu's magnificent colours on my Hyper terminal.
And I don't think I'm the only who agrees!

**Comment by dempfi** [comment]
Hi @victorronnow, there is this package https://github.com/ayu-theme/ayu-colors with ayu colors. I suppose it can be used to create hyper theme. But I don't use it will take a lot of effort for me to implement one.

**Comment by k15a** [comment]
I've updated the ayu-colors package so it matches the latest sublime theme. Feel free to use it.

**Comment by k15a** [comment]
You can check out https://github.com/licatajustin/hyper-ayu as well :)

**Comment by maticrivo** [comment]
any chance to update the colors? https://github.com/ayu-theme/ayu-colors/issues/6

**Comment by dempfi** [comment]
Hey @maticrivo, I’ll update them soon.

**Comment by maticrivo** [comment]
Thanks @dempfi. what about #174? can i help in some way?

**Comment by k15a** [comment]
@dempfi Now that you have the colors in a JavaScript file in this repo do we want to move the ayu-colors stuff into this repo as well? Do you have an npm account so I can give you the permissions to publish a new version to npm?

**Comment by dempfi** [comment]
@k15a I think best approach would be to move colors from this repo to ayu-colors and include it as a dependency here. That way we’ll guarantee up to date colors in one place. I would appreciate ability to publish ayu-colors. My npm login is `dempfi`. Thanks mate.

**Comment by k15a** [comment]
I've added you to https://www.npmjs.com/package/ayu. There was a request to rename this package to ayu-colors. Maybe this is worth considering now as well.
