### ISSUE TITLE
wrong icons

### ISSUE THREAD

**Issue by sobolevn** [dempfi/ayu#156]
Almost every icon is broken.
I have upgraded to the latest `auy`, removed `A File Icon` package.

<img width="219" alt="2017-09-21 14 34 59" src="https://user-images.githubusercontent.com/4660275/30693880-26df50c4-9eda-11e7-918b-834bb1e52e2e.png">

What else should I do?

Please, return me my favorite icons 🍺

**Comment by dempfi** [comment]
@sobolevn you have to install A File Icon back :) Ayu works in combination with it — A File Icon provides missing icons and some settings for ayu. I'll push updated set of ayu icons in few hours, keep tuned
