### ISSUE TITLE
Missing icons for .vue files

### ISSUE THREAD

**Issue by gwest4** [dempfi/ayu#157]
It seems that the icons for .vue files have gone missing:
![capture](https://user-images.githubusercontent.com/11031514/30751664-8c0a0a34-9f7f-11e7-8b66-f1fbc0666ddf.PNG)

[**Vue Syntax Highlight**](https://github.com/vuejs/vue-syntax-highlight): v3.2.3
**ayu**: v3.2.0
**Sublime**: 3.0, Build 3146
**Windows**: 10 Pro

**Comment by dempfi** [comment]
Hi @gwest4 just add package AFile Icon
