### ISSUE TITLE
Double-click on title bar to minimize doesn't work

### ISSUE THREAD

**Issue by benface** [dempfi/ayu#158]
This theme seems to break macOS's functionality to double-click on the title bar to minimize (this is a feature that can be turned on/off in "System Preferences > Dock > Double-click a window's title bar to minimize").

**Comment by dempfi** [comment]
This isn't the issue with the theme but with sublime itself. However, you can enable native title bar to fix the issue. Just put `"ui_native_titlebar": true` in your settings.

**Comment by benface** [comment]
Thank you, that works!
