### ISSUE TITLE
Color Scheme Error

### ISSUE THREAD

**Issue by atulbhats** [dempfi/ayu#16]
Hi. 

I followed the manual install method. 
Copied the files, 
edited the preferences as the following

```
{
	"font_size": 12,
	"theme": "ayu2.sublime-theme"
	"color_scheme": "Packages/ayu/ayu.tmTheme"
}

```

But I get the following error. 

![image](https://cloud.githubusercontent.com/assets/4313624/19155674/f099fa8c-8bfc-11e6-8608-36753a1aa5b7.png)

Help?

**Comment by dempfi** [comment]
hey @atulbhats, have you renamed folder to `ayu`, if yes can you add your ST and OS versions to question?

**Comment by diogobernini** [comment]
Aren't you missing a comma on the theme line?

**Comment by atulbhats** [comment]
@dempfi Yea! That fixed it. Thanks. That was stupid of me to not notice the name in the preference string.

@diogobernini Thanks. But that was an error in formatting while posting it here on this issue thread. 

Problem Solved. Issue Closed. :+1: :smile:
