### ISSUE TITLE
JS incorrect syntax highlighting

### ISSUE THREAD

**Issue by sobolevn** [dempfi/ayu#161]
I have faced an issue with `js` code highlighting. 

This code breaks the markup:
```js
var gulp = require('gulp'), // Enabling gulp
  sass = require('gulp-sass'),
  other = null;
```

![2017-10-10 21 39 56](https://user-images.githubusercontent.com/4660275/31404127-d89f3648-ae03-11e7-8f38-f2b2d9d14da6.png)

I am using the latest Sublime, the latest `ayu`.

**Comment by dempfi** [comment]
Hi @sobolevn, unfortunately I can't reproduce this issue with JS and gulpfile. This is what I have in my Sublime. Also, it seems you use some custom JS syntax highlighting plugin, it may be the source of the issue. 
<img width="378" alt="screen shot 2017-10-11 at 1 18 11 am" src="https://user-images.githubusercontent.com/4568573/31413511-45581a7a-ae22-11e7-8ea6-1cfba8226839.png">

**Comment by sobolevn** [comment]
Hm, indeed. Looks like https://github.com/babel/babel-sublime issue. Thanks.
