### ISSUE TITLE
disabled horizontal scroll

### ISSUE THREAD

**Issue by mrG0bliN** [dempfi/ayu#165]
![10-11-2017 01-40-01](https://user-images.githubusercontent.com/11839238/32633315-177657d6-c5b8-11e7-85e7-5e608fcc72c6.jpg)

pls add option to disable this scroll panel ♥

**Comment by dempfi** [comment]
Hey @mrG0bliN, do you mean to disable appearance of scrollbars?

**Comment by mrG0bliN** [comment]
I wish to clean visually, horizontal scrolling

**Comment by mrG0bliN** [comment]
mate? @dempfi pls give me little time and fix this riddle

**Comment by mrG0bliN** [comment]
dead issues 
close
