### ISSUE TITLE
Fuzzy title bar text after High Sierra upgrade

### ISSUE THREAD

**Issue by ghost** [dempfi/ayu#168]
Title bar text is fuzzy on dark themes after upgrading to High Sierra
All fonts are the same also tried on ST Dev build

<img width="297" alt="screen shot 2017-11-16 at 4 30 48 am" src="https://user-images.githubusercontent.com/6995878/32870964-0ab8d3ec-ca87-11e7-895f-7bb4697e3e35.png">

**Comment by dempfi** [comment]
Hi @mrunc, this is an issue with ST itself. However I'll try to adjust colors of title bar in next release to reduce the impact

**Comment by mrunc** [comment]
I downgraded to 10.12.6 again, lots of other issues with other apps as well.
I thought I delayed the High Sierra upgrade enough for issues to be fixed turns out I was wrong
