### ISSUE TITLE
ui_native_titlebar doesn't seem to work?

### ISSUE THREAD

**Issue by tuananh** [dempfi/ayu#169]
I set it to `false` but it's still using the native title bar.

how do i get the dark title bar like screenshot in readme?

thank you in advance.

**Comment by k15a** [comment]
You have to set it to true.

**Comment by tuananh** [comment]
i set it to true, restart and it's still the normal one. what i want to get is like this

![image](https://user-images.githubusercontent.com/627278/32992490-de326da2-cd7d-11e7-8299-8b8b8aa53f00.png)

What i have

![image](https://user-images.githubusercontent.com/627278/32992494-e5cdf180-cd7d-11e7-93b0-ac0e9e446948.png)

**Comment by k15a** [comment]
For me it's working without the options.

My config:

```json
{
	"color_scheme": "Packages/ayu/ayu-mirage.tmTheme",
	"ignored_packages":
	[
		"Vintage"
	],
	"theme": "ayu-mirage.sublime-theme"
}
```

**Comment by tuananh** [comment]
may i ask wha'ts your sublime version and build number?

**Comment by tuananh** [comment]
sorry i was using ayu-dark2. that option didn't work on dark2 but fine on dark.
