### ISSUE TITLE
[question] what's this weird highlight?

### ISSUE THREAD

**Issue by tuananh** [dempfi/ayu#170]
It looks like this

![image](https://user-images.githubusercontent.com/627278/32991820-2e168474-cd75-11e7-8830-9db6581a00fa.png)

options that i used
```
"ui_big_tabs": false,
"ui_fix_tab_labels": true,
"ui_font_default": false,
"ui_font_size_small": false,
"ui_native_titlebar": false,
"ui_separator": false,
```

**Comment by dempfi** [comment]
Hey @tuananh. This seems like a regression. I would address it in the next release which should be today :)
