### ISSUE TITLE
Icons not rendering in all ayu themes

### ISSUE THREAD

**Issue by meeps123** [dempfi/ayu#173]
Hi, in latest ayu version none of the icons are rendering even when entire master directory is placed under Packages/User, leaving behind a weird red outline.

![screenshot 135](https://user-images.githubusercontent.com/22002891/33359704-4171e48a-d50b-11e7-8c29-753fdf44a9c4.png)

I'm using Sublime Text 3 latest build 3143.

Could a fix for this be released in the next commit? Thanks.

**Comment by dempfi** [comment]
Hi @meeps123, I'm very sorry you have such issue. I would try to do my best to find the root cause and resolve it the next release.

**Comment by dempfi** [comment]
Hi @meeps123 can you please check if you still have the issue with ayu 4.0.0?
