### ISSUE TITLE
iterm color

### ISSUE THREAD

**Issue by maticrivo** [dempfi/ayu#174]
i know there are the iterm colors @dempfi uploaded more then a year ago [here](https://github.com/dempfi/ayu/issues/25#issuecomment-252255598) but im wondering if there is an updated one with more recent colors scheme and the mirage theme for iTerm?

**Comment by dempfi** [comment]
I’ll upload schemes I use in 20-30 mins. But I have to warn you that they aren’t quite polished and don’t match exactly the colors in the sublime theme just because what looks great in sublime doesn’t look the same way in the terminal apps’ outputs.

**Comment by dempfi** [comment]
[Archive.zip](https://github.com/dempfi/ayu/files/1545727/Archive.zip)

**Comment by maticrivo** [comment]
@dempfi thanks, they look great!

**Comment by amckinlay** [comment]
@dempfi Is there any way you can set up a permanent repo for ayu terminal colors so that was can get constant updates?
