### ISSUE TITLE
Minimap indicator almost invisible

### ISSUE THREAD

**Issue by lapega** [dempfi/ayu#177]
With the last Ayu update the minimaps indicator gets almost invisible. 
Is very difficult to see where is it.
![captura de pantalla de 2017-12-14 09-31-32](https://user-images.githubusercontent.com/572502/33992548-d371eedc-e0b1-11e7-874a-be9c13c9e48c.png)

**Comment by luco** [comment]
+1 on this. The previous was much better.

**Comment by dempfi** [comment]
Fixed in https://github.com/dempfi/ayu/releases/tag/4.0.1
