### ISSUE TITLE
Open quick panel (command palette) causes error in console

### ISSUE THREAD

**Issue by darkkain** [dempfi/ayu#178]
When open quick panel (command palette) this error spam few times in console: 
`no such prop font.bold for quick_panel_label`

Its seems that a problem in this lines:
 [ayu-dark.sublime-theme](https://github.com/dempfi/ayu/blob/master/ayu-dark.sublime-theme#L236) 
[ayu-light.sublime-theme](https://github.com/dempfi/ayu/blob/master/ayu-light.sublime-theme#L236)
[ayu-mirage.sublime-theme](https://github.com/dempfi/ayu/blob/master/ayu-mirage.sublime-theme#L236)
Because can't find `font.bold` properties in [sublime themes docs](https://www.sublimetext.com/docs/3/themes.html#filter_label_properties)

OSX High Sierra (10.13.2)
Sublime 3143

**Comment by dempfi** [comment]
https://github.com/dempfi/ayu/releases/tag/4.0.2
