### ISSUE TITLE
Theme applying only on the settings page (body)

### ISSUE THREAD

**Issue by diogobernini** [dempfi/ayu#18]
![capturar](https://cloud.githubusercontent.com/assets/3130370/19167340/a0b94b82-8be1-11e6-8b1f-72878339153f.PNG)

Settings as follow:
```
{
	"theme": "ayu.sublime-theme",
    "color_scheme": "Packages/ayu/ayu.tmTheme",
    "ui_separator":       true, // separators between panels
    "ui_font_size_small": true, // smaller UI font size(sidebar, statusbar etc)
	"detect_indentation": false,
	"font_size": 11,
	"ignored_packages":
	[
		"Package Control",
		"Vintage"
	],
	"tab_size": 4,
	"translate_tabs_to_spaces": true
}
```
Folder has been renamed. Sublime 3.

**Comment by dempfi** [comment]
try to set color scheme to default or any other and then back to ayu. happens sometimes with Sublime

**Comment by dempfi** [comment]
@diogobernini can you confirm that the issue is resolved, so I can close the issue?

**Comment by diogobernini** [comment]
Still does not fix the issue.

**Comment by dempfi** [comment]
OK @diogobernini, I suppose I know where the issue, can you tell me what plugin you are using to get syntax highlighting for that kind of `*.html` captured on your screenshot? I think It may have its own color scheme definition.

**Comment by diogobernini** [comment]
It was that! I was using "Color Highlighter " and it needed a specific theme choice. Thanks!
