### ISSUE TITLE
Insane computer lag when using this theme on Retina Macbook Pro

### ISSUE THREAD

**Issue by tdfranklinaz** [dempfi/ayu#180]
My computer started lagging like crazy when doing web dev and I couldn't figure out the issue for a long time. One day I decide to clean things out and disable the Ayu mirage theme and all my lag problems went away. Not sure why this was happening or if it was even a problem with the theme or maybe just a conflict but it made my i7 8gb ram Macbook pro retina lag and it wasn't usable at times.

**Comment by dempfi** [comment]
Hi @tdfranklinaz, I'm not sure I can do anything realistically about this. Maybe you could update to the latest version of sublime and see if it fixes the problem. Anyhoo, I'm sorry you had such an experience with ayu :/
