### ISSUE TITLE
Scroll bar is an odd color

### ISSUE THREAD

**Issue by zubricks** [dempfi/ayu#181]
I've seen this with some other themes, not sure what it is, but some styles not getting set or something? 
![screen shot 2018-01-22 at 1 48 36 pm](https://user-images.githubusercontent.com/26472106/35238258-f6a31902-ff7a-11e7-92a1-a589043553e7.png)

**Comment by dempfi** [comment]
Hi @zubricks. This means there is something wrong with the assets loading. Can you please confirm if the issue is still valid and how did you install the theme(via package control)?
