### ISSUE TITLE
Highlight active tab on bottom border

### ISSUE THREAD

**Issue by milepanic** [dempfi/ayu#182]
Hi, there was an update which changed active tab highlight to top border of tab. Is there any way to chagne it to bottom border?

**Comment by dempfi** [comment]
Hi @milepanic, If you turn off separators option, the border will be on the bottom.

**Comment by summer-street** [comment]
Is it possible to completely remove this orange line border? It seems to me just a brighter title for a tab is enough. Thank!

**Comment by andremacola** [comment]
@dempfi I would like to change the border to bottom but still have the separators because the sidebar. Is it possible?

**Comment by dempfi** [comment]
This has been improved in the recent versions, tabs with separators are highlighted differently.
