### ISSUE TITLE
Ayu breaks open_files_in_new_window option

### ISSUE THREAD

**Issue by tencircles** [dempfi/ayu#187]
Really odd, but after installing Ayu, sublime no longer respects the `open_files_in_new_window` option when set to false. Confirmed by switching back to default theme and everything behaves as expected. Any idea what might cause this?

**Comment by dempfi** [comment]
Hm, this is odd indeed. Will check what's going on.

**Comment by icandyman** [comment]
open-file in your new tab ::: i thinks its solve :::

**Comment by dempfi** [comment]
Can't reproduce with latest version of ST and ayu. If you still experience the problem, please feel free to reopen this issue.
