### ISSUE TITLE
How about adding a light version with a mix of solarized colors?

### ISSUE THREAD

**Issue by THPubs** [dempfi/ayu#188]
Just did some modifications and added solarized background colors. Let me what you think. If good I can make a pr 😄 

<img width="1518" alt="screen shot 2018-04-12 at 6 23 24 am" src="https://user-images.githubusercontent.com/1212023/38653975-dfcc4160-3e2a-11e8-85e9-29a42beeba92.png">

**Comment by mrG0bliN** [comment]
no, mirage better

**Comment by dempfi** [comment]
not sure tbh. never was a fan of solarized themes :)

**Comment by THPubs** [comment]
@dempfi No issues 😄 Is it ok if I create a separate theme?

**Comment by dempfi** [comment]
@THPubs of course. This project is OSS for a reason :)
