### ISSUE TITLE
Overlapping statusbar

### ISSUE THREAD

**Issue by schnittstabil** [dempfi/ayu#19]
The status bar is overlapping on Linux, ST Build 3126:
![status-bar](https://cloud.githubusercontent.com/assets/6059032/19169641/a4f67240-8c15-11e6-8b56-070fc506b241.png)

Maybe related to #4?

Awesome theme, btw.

**Comment by dempfi** [comment]
Duplicate of https://github.com/dempfi/ayu/issues/12
