### ISSUE TITLE
Please add the feature to control the width of the status bar.

### ISSUE THREAD

**Issue by piyuple** [dempfi/ayu#190]
The **status bar** is taking way more space than I want it to. Please add a way to control its **width**.

**Comment by dempfi** [comment]
Hey @piyuple, can you please share a screenshot?

**Comment by piyuple** [comment]
![statusbar](https://user-images.githubusercontent.com/11230167/40282243-037d21c4-5c8a-11e8-92c7-97efe3f6514b.JPG)
As you can see, the status bar occupies a lot of space at the bottom.

**Comment by dempfi** [comment]
I made it a bit smaller recently, hope it fixes your issue. If not, I'll consider adding a settings, tho I'm not a fan of customization settings — they are pain in the ass to maintain.

Closing the issue for now, feel free to reopen.
