### ISSUE TITLE
Gutter color is a different color compared to theme

### ISSUE THREAD

**Issue by nikitavoloboev** [dempfi/ayu#192]
I use Ayu Mirage theme in Sublime and the Gutter on the left side is of `#1C222C` color. When it should be `#212733` instead.

Here is how it looks for me:

![2018-06-08 at 18 52](https://user-images.githubusercontent.com/6391776/41170576-2d894bce-6b4d-11e8-896f-0308b4c38b96.png)

I found these settings that change the Gutter color that I think may work:

```json
{
    "rules":
    [
        {
            "scope": "markup.deleted.git_gutter",
            "foreground": "#212733"
        },
        {
            "scope": "markup.changed.git_gutter",
            "foreground": "#212733"
        },
        {
            "scope": "markup.inserted.git_gutter",
            "foreground": "#212733"
        },
        {
            "scope": "markup.ignored.git_gutter",
            "foreground": "#212733"
        },
        {
            "scope": "markup.untracked.git_gutter",
            "foreground": "#212733"
        }
    ]
}

```

Can this be added to the theme please? Thank you.

**Comment by dempfi** [comment]
@nikitavoloboev do you still experience this issue?

**Comment by nikitavoloboev** [comment]
> do you still experience this issue?

I do still experience it but I learned to like it so it's fine. 🙂

**Comment by dempfi** [comment]
> but I learned to like it so it's fine

Best workaround ever 😅
