### ISSUE TITLE
"Error loading color scheme" occurs when Ayu is set to be Sublime's scheme

### ISSUE THREAD

**Issue by lee-ho** [dempfi/ayu#193]
This Two alerts like one on the screenshot appeared when I set the scheme. Also the icons of folders was lost, or rendered incorrect, same as headers of tabs. After relaunching Sublime the problem disappeared.

<img width="1180" alt="screen shot 2018-06-28 at 22 50 41" src="https://user-images.githubusercontent.com/6252665/42060359-d2d85b2c-7b26-11e8-8487-c7536814cd1b.png">

**Comment by dempfi** [comment]
Hi @lee-ho, this happens when ayu is being updated in the background. Unfortunately I can't do much about this and, as you already found out, simple relaunch fixes the issue.
