### ISSUE TITLE
selection color plz make brighter more prominent

### ISSUE THREAD

**Issue by xbipin** [dempfi/ayu#194]
i started using this theme recently and the one thing that bugs me a lot is suppose u want to select some portion of code the background of that selection isnt prominent, its more like a very light blue color making it harder to view what u have selected

**Comment by dempfi** [comment]
Hi @xbipin, can you please check v5? I've fixed a lot of contrast issues in regards to the selection colours. They should look better now. Please feel free to reopen the issue if you are not satisfied and there is still some room for improvements.

**Comment by xbipin** [comment]
i tried v5.0.1 and using ayu-mirage color scheme but still when i select some piece of code, the background is a light shade of blue but the foreground text is also little light so still its not prominent. i would prefer making the selected text foreground a little richer if u plan to keep the light blue as selected background or rather invert the color of text and make background color much richer
