### ISSUE TITLE
Sublime's about box is no longer readable when Ayu Light is on

### ISSUE THREAD

**Issue by brainplot** [dempfi/ayu#196]
Hi, this is a very minor thing but I wanted to report it anyway.
I use the light version of the theme and I happened to click on `Help > About Sublime Text` and found out that the words "Sublime Text" are completely white, on a white background.

This is what it looks like with the Sublime's _default_ theme:

![default](https://user-images.githubusercontent.com/28014843/47033753-eb11ef00-d175-11e8-813c-5116760bfd78.PNG)

This is what it looks like when I set Ayu Mirage as my theme:

![ayu-dark](https://user-images.githubusercontent.com/28014843/47033791-ffee8280-d175-11e8-839a-0f820a571cce.PNG)

This is what it looks like when I set Ayu Light as my theme:

![ayu](https://user-images.githubusercontent.com/28014843/47033815-0d0b7180-d176-11e8-92df-5fc7559e2ada.PNG)

**Comment by dempfi** [comment]
Fixed in [v5.0.1](https://github.com/dempfi/ayu/releases/tag/5.0.1)
