### ISSUE TITLE
colors in screenshots are incorrect

### ISSUE THREAD

**Issue by amckinlay** [dempfi/ayu#197]
For example, the background color of ayu-mirage is (33, 39, 51) in sRGB, but in the screenshot it is (32, 39, 52).

The screenshots in https://github.com/ayu-theme/ayu-colors are correct.

**Comment by dempfi** [comment]
This is a tricky business — I take screenshots on my MacBook which is in P3 mode, however screenshots later converted to sRGB. I don't pay a lot of attention to the coloring in the screenshots since they are there just to give an idea of how the theme will look like.
