### ISSUE TITLE
Icons extension Rails (.erb) and Html (.html )

### ISSUE THREAD

**Issue by padualima** [dempfi/ayu#199]
I really liked this theme, but I missed the HTML and ERB, could you please add?

![captura de tela 2018-11-19 as 15 43 07](https://user-images.githubusercontent.com/31924649/48728144-e75d0680-ec12-11e8-8659-89f534e34ab5.png)

**Comment by cannikin** [comment]
@padualima Have you looked lately? I just installed yesterday and I've got .erb and .slim icons:

![image](https://user-images.githubusercontent.com/300/53828097-8cd18700-3f31-11e9-8ccb-59507a4a8307.png)

**Comment by dempfi** [comment]
@padualima closing, since I can't repro the issue — all icons work are present and work fine.

**Comment by kaansoral** [comment]
On a clean sublime text installation, I'm missing the .html icon too
