### ISSUE TITLE
Sublime 2 compatibility

### ISSUE THREAD

**Issue by dempfi** [dempfi/ayu#2]
Normal
![screenshot 2016-10-03 19 13 59](https://cloud.githubusercontent.com/assets/4568573/19046662/17e10656-89a7-11e6-9c84-10f4cd250be9.png)

With `ayu`
![screenshot 2016-10-03 19 14 44](https://cloud.githubusercontent.com/assets/4568573/19046648/056e544c-89a7-11e6-84eb-55aa9671b0eb.png)

**Comment by ctf0** [comment]
tab labels are truncated , check 

https://camo.githubusercontent.com/fb5f7fda1b259389eff3674449772fee34a5af5f/687474703a2f2f692e696d6775722e636f6d2f30434c493344482e706e67

**Comment by dempfi** [comment]
closed in https://github.com/dempfi/ayu/pull/6
