### ISSUE TITLE
Warn/Errors from SublimeLinter

### ISSUE THREAD

**Issue by davidmatas** [dempfi/ayu#20]
Could be warns/errors from SublimeLinter showedd in a more standar way (yellow/red)? 
Actually it is showed in blue:

<img width="172" alt="captura de pantalla 2016-10-06 a las 23 07 46" src="https://cloud.githubusercontent.com/assets/271760/19170774/fecccb30-8c19-11e6-9b82-f0f27c5e7bac.png">

Nice theme!

**Comment by dempfi** [comment]
Hi @davidmatas, this is a bug actually :), thanks for report, this will be fixed in next release.

**Comment by dempfi** [comment]
Fixed in https://github.com/dempfi/ayu/pull/28
