### ISSUE TITLE
More emphasis on compile errors decorator

### ISSUE THREAD

**Issue by Remillard** [dempfi/ayu#201]
I like Ayu as an alternative to the DA CS schemes that have vanished.  One aspect though that seems to be missing is a color highlight for compile time errors.  For example, here's one compile time Sublime decorator example:
![image](https://user-images.githubusercontent.com/28012313/51500391-65649780-1d93-11e9-8119-026b8a5194ef.png)
The op up seems to be very faintly lighter than the background but even a dark maroon or something might make it pop a little bit more visually.  That would be handy for compiling and scanning the file for the errors.

**Comment by dempfi** [comment]
Hi @Remillard, what OS are you using? I have a distinct border and shadows around my popups.
<img width="560" alt="Screen Shot 2019-03-24 at 8 02 18 AM" src="https://user-images.githubusercontent.com/4568573/54875628-27273b00-4e0b-11e9-9dee-1310b76fe2f6.png">

**Comment by Remillard** [comment]
Windows 10.  Looking at your example, I don't think there's much difference.  I suppose I would like something with a little more contrast than the background is all.  It's just a suggestion

**Comment by dempfi** [comment]
This has been improved in the recent versions
