### ISSUE TITLE
Sublime Merge theme

### ISSUE THREAD

**Issue by schrodincat** [dempfi/ayu#204]
Would be nice to have a matching theme for Sublime Merge. It uses [the same format](https://www.sublimemerge.com/docs/themes) as Sublime Text does.

**Comment by dempfi** [comment]
Hi @schrodincat, it would be nice to do that theme, tho it would take a lot of time which I don't have. But if you're willing to work on it, I would gladly support in any way I can.

**Comment by schrodincat** [comment]
@dempfi yes, I'm moving to Sublime Merge myself, so I'm actually going to try to port it there.

However, I'm not a designer, so I'm not yet sure if I'm gonna to be able to do that. Either way, I'll post about a progress here.
