### ISSUE TITLE
Make "ayu dark" match macOS 12.14 Mojave Dark Mode™

### ISSUE THREAD

**Issue by matthewmorek** [dempfi/ayu#205]
I understand this is a bit opinionated, but have you considered making ayu dark match the native macOS Mojave dark theme?

IMO, it would nicely fit in with other applications on the platform, and I believe would be closer to what native apps in Windows 10 Fluent Design system look like, so two birds with one stone.

I'll be happy to work on the PR, as I believe altering ayu dark to match Cocoa Dark Mode would not be too big of a job, would it? Especially now, that ST3 officially supports Mojave's transparency, etc.

**Comment by dempfi** [comment]
Hi @matthewmorek, I did consider this a bit a while ago, tho, TBH I don't really like macOs dark background colour — it's very dirty. What would be possible, I think, is to add another colour scheme forked from dark but with macOs backgrounds. If you do want to work on such a PR, I would gladly accept it.
