### ISSUE TITLE
File name tab error and Side Bar folder Icon no display 

### ISSUE THREAD

**Issue by erzqy** [dempfi/ayu#208]
Sublime Text 3.1.1 Build 3176
Windows 10 x64 1809 Build 17763.379
Ayu 5.0.1 (auto upgrade via Package Control recently)

# Filename Tab (or just tab)
Invisible caption or file name and also have no close button.

# Folder icon in Side Bar
The file icon is look good but the folder tree icon.

**Comment by dempfi** [comment]
Hi @erzqy, please upgrade your ST to the latest version which is 3200. That should solve your problem, if doesn't feel free to reopen the issue.

**Comment by erzqy** [comment]
that's solve this problems, cause of new feature on side bar.
which is ST under build 3200 no longer compatible with the newly version of Ayu theme. thanks
