### ISSUE TITLE
UI font settings

### ISSUE THREAD

**Issue by CodeDotJS** [dempfi/ayu#209]
What's the reason behind the removal of UI font settings? 

- `(ui_font_size_small, ui_font_source_code_pro, ui_font_roboto_mono)`

To be honest, this was a cool feature and seeing it getting removed from the latest release was confusing.

**Comment by dempfi** [comment]
Hi @CodeDotJS, it was really much harder to maintain those options given I don't really have a lot of time to work on ayu. If you with to use monospaced font in the UI, I probably can write a small guide how to do that with any theme.

**Comment by CodeDotJS** [comment]
Yes, a small guide would be better, and it would be really helpful if you include it in the documentation. I think a lot of people who use Ayu take the option of UI font as one of the reasons to love it. 

Also, thank you very much for creating this awesome theme, it's my favourite, and I really appreciate the hard work you are putting to maintain this repository. 

Once again, thank you!

**Comment by schrodincat** [comment]
> I probably can write a small guide how to do that with any theme

Is there a way to tweak those settings without changing original `ayu` files though? I don't believe there is a system similar to hierarchy of `.sublime-settings` files for themes. And if there is not, all changes would be rewritten on next `ayu` update by Package Control.

**Comment by schrodincat** [comment]
@CodeDotJS to use Roboto Mono font again just add 3 files in your `Packages/User` directory named `ayu-light.sublime-theme`, `ayu-mirage.sublime-theme`, `ayu-dark.sublime-theme` with the following content:
```
[
    {
        "class": "tool_tip_label_control",
        "font.face": "Roboto mono"
    },
    {
        "class": "tab_label",
        "font.face": "Roboto mono"
    },
    {
        "class": "sidebar_heading",
        "font.face": "Roboto mono"
    },
    {
        "class": "sidebar_label",
        "font.face": "Roboto mono"
    },
    {
        "class": "label_control",
        "font.face": "Roboto mono"
    }
]
```

**Comment by schrodincat** [comment]
However, there seem to be an issue with it, as last symbol in status bar is consistently cut off:
<img width="1185" alt="Screenshot 2019-03-24 at 17 22 25" src="https://user-images.githubusercontent.com/13354491/54880745-75632b00-4e59-11e9-8ddd-5dbaed784db1.png">

**Comment by thang-nm** [comment]
@dempfi Font setting guide please. Thank you so much!

**Comment by dempfi** [comment]
@thang-nm, I was gonna write almost the same thing as @CodeDotJS already did :), tho will put it in the readme.

**Comment by dempfi** [comment]
So, @CodeDotJS here you go https://github.com/dempfi/ayu#custom-ui-fonts. Closing the issue now, feel free to reopen if something related pops up :)

**Comment by CodeDotJS** [comment]
Although, I managed to figure it out, but thank you for adding the solution in documentation. 

Thank you @dempfi @schrodincat
