### ISSUE TITLE
Inactive tabs are hard to see

### ISSUE THREAD

**Issue by ankurk91** [dempfi/ayu#21]
It is hard to see inactive tabs, how can i tweak the color ?

![screenshot from 2016-10-07 10-07-51](https://cloud.githubusercontent.com/assets/6111524/19179010/6bb5b00c-8c76-11e6-8f5a-5aaf0c426493.png)

* Sublime 3 x64 (latest beta)
* Ubuntu 16.04 x64
* Dark theme

**Comment by dempfi** [comment]
Can you please check version of `ayu`? In 1.2.0 I've already tweaked contrast of colors.

**Comment by ankurk91** [comment]
I re-installed ayu 1.2.0 from package control, still same result.
I keep 30 cm distance from my screen.

Is it possible to change inactive tab backround color to something else instead of changing text color.
![screenshot from 2016-10-08 09-07-21](https://cloud.githubusercontent.com/assets/6111524/19210101/acc0fde8-8d36-11e6-9013-d50497b1cc6c.png)

See sublime does the same by default, file names are visible enough on inactive tabs.
