### ISSUE TITLE
UI always use Light theme colors

### ISSUE THREAD

**Issue by Solganis** [dempfi/ayu#210]
Hi! Was using Ayu for like 5 months now and after update to 3200 Sublime Text 3 UI broke and always use a Light theme colors. But I was sitting on a "Mirage" theme all the time. 

Activating Material theme or any of the default ones - work's like a charm.
Trying to rollback to 3176 Sublime with clear install - didn't help at all. :(

[added screenshot](https://i.imgur.com/eClwX4s.png)

**Comment by dempfi** [comment]
Seems like an update issue, could you try to completely remove ayu and install it again. Also, activate ayu via adding following to your settings

```json
"theme": "ayu-mirage.sublime-theme",
"color_scheme": "Packages/ayu/ayu-mirage.sublime-color-scheme",
```

**Comment by Solganis** [comment]
I remove package (reopen app) and reinstall it via package control, same result :(

[There is a screenshot](https://d1ro8r1rbfn3jf.cloudfront.net/ms_59291/RRi99abetV2G0NOxE0l93o03liYIl4/2.png?Expires=1553529600&Signature=s2n-C4rqRqWdc4GfLRe2Z2NgDjZ6W-eNVhtk89NFr0g7zBH56Wl6IcSvyyxWwgZGWytolHegMnMHsj1Ke~Qab-3-VaFEDZVOZUltU24d~nTPzj6u79nkKJisWkiSsZII6eNUx943EnCsKdrNIpKF6ckcJlVg2NvSS3r1mehyjYrJ2lFHwZNp0wFHN~AscP72OatNA8FjafOxy2seTRQzF8uJjY3w5iTTqdbjYdMMQSOr9JeRcg7LsFkLgPNhvR-YuXOtPSqsCkSNEbR5qi2xJsLc0Iq8XDoLw3F5uLfULqcT1HZA2rWv1zrDcUwkhjgGrpcW1gwEDzvEIziqeINkGw__&Key-Pair-Id=APKAJBCGYQYURKHBGCOA)

**Comment by dempfi** [comment]
Seems like a caching issue. Could you try to clean Cache directory?

Open command pallets and type in `browse packages`, you'll see a directory named `Cache`. Remove everything from that directory, relaunch ST and activate the theme again. Hopefully, that will do the trick.

**Comment by Solganis** [comment]
I didn't have a `Cache` folder in `Packages` folder, but if I go one folder UP there it is and I deleted it. (MAC OS)

Nevertheless, [it didn't help at all](https://d1ro8r1rbfn3jf.cloudfront.net/ms_59291/OcIJ51LzqPROU6dpNQIY35c9OOAkaJ/3.png?Expires=1553531400&Signature=EP19-IGnOoQoJ5~A0umlWxYn4s-T1i59f~XIlJVM6SfDyjBDfI65EYogGhcQJDupQc4luLFTfEp2COU0SSLJuCE7ex2Za1Ct91MvB8ROuzAjpV7mLeuHUAH8uiNM90TpEVDM2AU7ZetGDycyfa4DBx8dmsdUO6kkk2i5svWauqR6Y8yQhAPctWZrH4TEhJNN~gL6pkaPA9cD-TdfKpFsxH3bPxLgvtK0Dd10HKcFl3msoSIVYvYwh4i6ACYzLr4MIU-X5Bp-Z~cKklMgOIJBZsmCPoyOtNFVocchuAkCUVYTBfI75XKWrZBSp0bS1rWqjDjj7biiUphfojizTr4KJg__&Key-Pair-Id=APKAJBCGYQYURKHBGCOA). :( It's sad.

**Comment by dempfi** [comment]
Not sure what to suggest except clean reinstall, seems like the UI theme was not applied. What you have on screenshot isn't the light theme.

**Comment by Solganis** [comment]
Thanks for trying to help! Much appreciated.
