### ISSUE TITLE
broken design build 3200

### ISSUE THREAD

**Issue by ryuta69** [dempfi/ayu#212]
sorry if it's still in progress, or already released patch.
<img width="1432" alt="スクリーンショット 2019-03-26 5 13 25" src="https://user-images.githubusercontent.com/41639488/54951109-2ff04c00-4f86-11e9-8b97-b3a3ce696ca0.png">

**Comment by dempfi** [comment]
Could you try to reinstall the theme via package control?

**Comment by lambertjosh** [comment]
Uninstalling and reinstalling does fix it. :+1:

**Comment by lehni** [comment]
I'm experiencing the same problem, and reinstalling doesn't work for me. I use ayu-light, and still see dark syntax highlighting in a light UI after reinstalling / restarting Sublime Text 3.2

**Comment by ryuta69** [comment]
Thank you! It's solved!
Sorry that I didn't try reinstalling before asking.
