### ISSUE TITLE
issues with release 5.0.3

### ISSUE THREAD

**Issue by ttrasta** [dempfi/ayu#213]
When selecting any of the themes (light, mirage, dark), the tab bar and sidebar are not changed. In the screenshot selected dark theme.
![1](https://user-images.githubusercontent.com/32821959/55032883-eb66be00-5022-11e9-808d-0d3a5b17f8d5.JPG)

**Comment by nickodell** [comment]
I have a similar issue - I can select any ayu theme except for ayu light. Ayu was updated recently, and I got an error message at the same time:

    The package containing your active theme was just upgraded.

    The package containing your active color scheme was just upgraded. However, the .tmTheme file no longer exists. Sublime Text has been configured use the default color scheme instead.

(Not an exact transcription - I couldn't copy paste the message.)

**Comment by dempfi** [comment]
It’s sublime caching behavior. You probably will have to clean sublime’s cache. Clean reiantallation of sublime should do the trick.

**Comment by ttrasta** [comment]
I decided to just reinstall the sublima text (I just use the portable version). And it really helped. thank

**Comment by ttrasta** [comment]
> I have a similar issue - I can select any ayu theme except for ayu light. Ayu was updated recently, and I got an error message at the same time:
> 
> ```
> The package containing your active theme was just upgraded.
> 
> The package containing your active color scheme was just upgraded. However, the .tmTheme file no longer exists. Sublime Text has been configured use the default color scheme instead.
> ```
> (Not an exact transcription - I couldn't copy paste the message.)
> 
> Uninstalling and reinstalling, like #212 suggests, does not help.

Most likely, the reinstallation did not help you, because you didn’t clean the remaining folders on the C drive.

**Comment by Julchu** [comment]
I'm having the same problem

How do you clean the cache without reinstalling Sublime?

**Comment by nickodell** [comment]
Thanks for the advice, and the great theme, @dempfi . I got it working by reinstalling Sublime Text, then going into `~/.config/sublime-text-3`, and deleting the directories `Cache`, `Installed Packages`, `Backup`, and `Lib`. Then I reinstalled ayu and typed 'ayu: activate theme' in the command palette.

**Comment by StarHack** [comment]
I faced exactly the same problem. It turned out I simply had to **update** Sublime Text 3 (from 3.1.1, Build 3176) to the current version which is 3.2, Build 3200).

**Comment by mrG0bliN** [comment]
Fixed after install 3200 version!

**Comment by itaffy** [comment]
The left sidebar cannot display the icon
![image](https://user-images.githubusercontent.com/36696565/55299929-d8f7e480-5467-11e9-8c7c-817b7cf9f315.png)

**Comment by dempfi** [comment]
Glad the issue got resolved for you guys. Closing.
