### ISSUE TITLE
UI font size is bigger in last release (5.0.3)

### ISSUE THREAD

**Issue by lapega** [dempfi/ayu#215]
In the new release of Ayu theme, the fonts in tabs, sidebar and status bar are bigger than before, and the rest of the UI.
Is there a setting to change it to a smaller size?
I have this:

> "ui_big_tabs": false,
> "ui_fix_tab_labels": true,
> "ui_font_default": true,
> "ui_font_roboto_mono": false,
> "ui_font_size_small": true,
> "ui_font_source_code_pro": false,
> "ui_separator": false,
> "ui_sidebar_highlight_row": true,
> "ui_wide_scrollbars": false,

Thanks in advance!

**Comment by dempfi** [comment]
Hi @lapega. Yep, most of the options related to the font settings were removed (it was getting hard to maintain). Available settings are described here https://github.com/dempfi/ayu#settings.

To get smaller font size, here is an instruction for you:

1. Pull up command pallete via <kbd>cmd/ctrl</kbd> + <kbd>shift</kbd> + <kbd>p</kbd>
2. Type in `Browse packages`
3. Navigate to the `/User` folder
4. Create a file named `ayu-mirage.sublime-theme` to modify mirage or `ayu-light.sublime-theme` and `ayu-dark.sublime-theme`
5. Open that file in Sublime
6. Copy and paste following content:
   ```json
   [
    {
      "class": "tab_label",
      "font.size": 11
    },
    {
      "class": "sidebar_label",
      "font.size": 11
    },
    {
      "class": "label_control",
      "font.size": 11
    },
    {
      "class": "tool_tip_label_control",
      "font.size": 11
    }
   ]
   ```
7. Replace `PragmataPro Mono Liga` with the font of your choice
8. Save and enjoy :)

**Comment by lapega** [comment]
It works!
Thank you!!!
