### ISSUE TITLE
Theme switching leaks memory

### ISSUE THREAD

**Issue by schrodincat** [dempfi/ayu#216]
Theme switching leaks memory on macOS 10.14.4 and Sublime Text 3204.

Here is [the video demonstrating the issue](https://www.icloud.com/iclouddrive/0CqYdDWy5YiOtYbcaiELcm6oQ#Screen_Recording_2019-04-02_at_21.50).

Probably upstream, but maybe you'll be able to help to diagnose the underlying issue.

Here is related [discussion in Sublime Text forum](https://forum.sublimetext.com/t/memory-leak-on-switching-themes/43135).

**Comment by dempfi** [comment]
Hey there, not sure how what to do about this — I did recently start using new theme format. Maybe that's the cause.

**Comment by schrodincat** [comment]
Fixed upstream in 3208
