### ISSUE TITLE
I would like to change the color of @CitationKeys

### ISSUE THREAD

**Issue by NatalieGates** [dempfi/ayu#217]
I would like to change the color of the citation keys (i.e, @CitationKey2019). Is this an easy fix? I'm using markdown.

![Screen Shot 2019-04-02 at 5 35 46 PM](https://user-images.githubusercontent.com/47909481/55437879-10e94f80-556e-11e9-8b9d-5b2dd6457f32.png)

**Comment by NatalieGates** [comment]
I noticed you already have this setup in Visual Studio Code:

![Screen Shot 2019-04-02 at 5 42 14 PM](https://user-images.githubusercontent.com/47909481/55438155-e350d600-556e-11e9-845f-b96879f2386c.png)

**Comment by dempfi** [comment]
Hi @NatalieGates, unfortunately sublime's default markdown syntax highlighter doesn't, unlike VSCode's, differentiate regular text and citation keys to be able to style them.

You can install MarkdownEditing extension (popular alternative to default one) and select Markdown GFM for markdown highlighting. Then citation keys will get highlighted.
