### ISSUE TITLE
Dark theme activated but search / title / files in white

### ISSUE THREAD

**Issue by dantegt** [dempfi/ayu#218]
When I installed AYU for the first time, I was able to activate the dark theme. A few days ago something changed and now I see title bar, search bar and files with white background. That doesn't ocurr with default skin. I tried re-installing it but it didn't fix it. I'm on Windows.
![ayu-dark-but-white](https://user-images.githubusercontent.com/8105616/56377336-957bd500-61e0-11e9-8a32-7913a5cd265a.jpg)

**Comment by mazentouati** [comment]
I'm facing the same problem too.

**Comment by WinstonN** [comment]
@dantegt @mazentouati I had the same issue, but upgraded sublime 3 to the latest version, and now it works - try it

**Comment by dantegt** [comment]
Thanks @WinstonN!
