### ISSUE TITLE
Support for Rstudio with tmtheme file

### ISSUE THREAD

**Issue by davidgibsonp** [dempfi/ayu#224]
Ayu Mirage is my go to theme for all my editors (sublime & vs code) but I have not been able to find a good alternative for Rstudio which is where I spend much of my time. I have tried recreating it with this [thTheme editor](https://tmtheme-editor.herokuapp.com/#!/editor/theme/Monokai) but have not been able to get close enough. 

Is there a tmtheme file for the Ayu themes anywhere or plans to create on? If not are there any suggestions to properly recreate it my own?

Thanks!

**Comment by jhaltiga** [comment]
Interested to know about this as well as it was featured as workable with Rstudio here: 

https://blog.rstudio.com/2018/10/29/rstudio-ide-custom-theme-support/

**Comment by davidgibsonp** [comment]
I actually just recently ported the ayu themes over to rstudio. finally bit the bullet and did it manually. But now I have the `.tmTheme` files along with `.rstheme`. Actually should close this issue...

Here is the repo [ayu-rstudio](https://github.com/davidgibsonp/ayu-rstudio)
