### ISSUE TITLE
Currently highlighted line is barely highlighted in the dark themes

### ISSUE THREAD

**Issue by alexanderadam** [dempfi/ayu#225]
The current colour for the highlighted line barely highlights the current line and makes this feature basically nonfunctional.
I can see the highlight in the `light` theme but `mirage` and `dark` is barely visible.

So it would be nice to make the current line better visible for those who activated the highlight line setting.

PS: thank you for your work :pray:

**Comment by dempfi** [comment]
Closed in https://github.com/dempfi/ayu/pull/251
