### ISSUE TITLE
No icons in the sidebar

### ISSUE THREAD

**Issue by SoullessWaffle** [dempfi/ayu#23]
Hey, I just installed the theme and unfortunately it doesn't look like the icons in the sidebar are showing:
![no icons in the sidebar](http://puu.sh/rAIE7/63dd6b2fe4.png)

As you can see it looks quite different from the screenshot in the README:
![screenshot in the README](http://i.imgur.com/r1mqHyx.png)

These are my settings:
![my settings](http://puu.sh/rAIRZ/cbaa3d6f28.png)

I'm on Windows 10, running Sublime Text 3 Stable build 3126.

How can I make my Sublime look more like the screenshot in the README?

**Comment by dempfi** [comment]
Hi @SoullessWaffle.
Can you please confirm that you don't see any folder icons beside folders too? Also note that filetype icons will appear only if you have syntax highlighting for specific language. However I obviously can see you have highlighting for css without icon for `*.css` file.

To make Sublime look more like in screenshot, first of all install [Roboto Mono](https://www.google.com/fonts/specimen/Roboto+Mono) for monospaced font in UI.
and here is my settings:
```json
{
	"caret_extra_bottom": 0,
	"caret_extra_top": 0,
	"caret_extra_width": 1,
	"caret_style": "phase",
	"color_scheme": "Packages/ayu/ayu-light.tmTheme",
	"font_face": "Roboto Mono",
	"font_size": 12,
	"highlight_line": true,
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 2,
	"line_padding_top": 2,
	"theme": "ayu-light.sublime-theme",
	"ui_font_size_small": false,
	"ui_separator": true
}
```

**Comment by SoullessWaffle** [comment]
Hi @dempfi 
Interesting! If I add a folder to the project, I can see the icons for the folder and all subfolders/files within it. It looks like _there's just no icons for non-project files_.
Thanks for sharing your settings file, it looks a lot better now!

**Comment by brightonmike** [comment]
On a Mac, I can't get the icons to show either. I've tried adjusting the settings. I have Roboto Mono installed. This is my settings. I'm using Text2.

`{
    "caret_extra_bottom": 0,
    "caret_extra_top": 0,
    "caret_extra_width": 1,
    "caret_style": "phase",
    "color_scheme": "Packages/ayu/ayu.tmTheme",
    "font_face": "Roboto Mono",
    "font_size": 12,
    "highlight_line": true,
    "indent_guide_options":
    [
        "draw_normal",
        "draw_active"
    ],
    "line_padding_bottom": 2,
    "line_padding_top": 2,
    "theme": "ayu2.sublime-theme",
    "ui_font_size_small": false,
    "ui_separator": true,
	"ignored_packages":
	[
		"Vintage"
	]
}`

**Comment by dempfi** [comment]
Hi @brightonmike, your case is different — ST2 doesn't support file type icons.

**Comment by brightonmike** [comment]
Ah, I see. I'll try 3 then. Cheers :)

**Comment by dempfi** [comment]
good new @SoullessWaffle, found the root of the issue. it's a conflict with another ui theme. if you have installed something like Material Theme or anything, try to remove it via Package Control

**Comment by SoullessWaffle** [comment]
@dempfi it doesn't look like I have any other themes installed, or at least Package Control doesn't list any.

**Comment by dempfi** [comment]
hey @SoullessWaffle, I tried to reproduce the issue on Win machine again and I failed to do so. I close this issue and I'm sorry that you can't enjoy full experience

**Comment by gTempesta** [comment]
@dempfi: Removing Material Theme solved my issue too.
Anyway, typing "cmd k, cmd b" or going to View > Side Bar > Show Side Bar is a quick fix (not working on drag & drop though).
