### ISSUE TITLE
Mirage: More prominent highlight background color for suggestions and command palette

### ISSUE THREAD

**Issue by mischnu** [dempfi/ayu#230]
Is there a way to make the highlight background color (e.g. in the suggestions pop-up or the command palette) more prominent?

I find it hard to tell which one is currently highlighted. Especially when there are only two options, I tend to consider the lighter unselected item as selected (see suggestions screenshot).

__Command palette__
![Command palette](https://user-images.githubusercontent.com/16582720/71243266-427a9480-2310-11ea-940c-58f12e39768a.png)

__Suggestions__
![Suggestions](https://user-images.githubusercontent.com/16582720/71243282-4c9c9300-2310-11ea-817f-e3d51bcfdf4b.png)

**Comment by dempfi** [comment]
This has been addressed in recent versions
