### ISSUE TITLE
CudaText support

### ISSUE THREAD

**Issue by Alexey-T** [dempfi/ayu#232]
Hi, good looking themes, even 2 dark variants are here. Could you, pls, make the same for CudaText?
https://wiki.freepascal.org/CudaText#Color_themes

**Comment by dempfi** [comment]
Right now I officially support ports to Visual Studio Code and Visual Studio. Under the https://github.com/ayu-theme we also have community-driven variants for vim and ace, and there are plans for XCode. As you can imagine that's quite a lot of projects to support and update. If there's a champion to lead maintenance work on Cude port, I can help get started.

**Comment by Alexey-T** [comment]
OK thanks.
