### ISSUE TITLE
[Feature Request] Option to change sidebar_label

### ISSUE THREAD

**Issue by Stanzilla** [dempfi/ayu#235]
Would love to see an option to change the `sidebar_label` font size inside of the theme. Or is it only possible with a custom sublime-theme file?

**Comment by dempfi** [comment]
@Stanzilla can you elaborate on what sizes you are looking for? This is possible and more a less straightforward to support but I'm looking to learn more on the issue itself

**Comment by Stanzilla** [comment]
Hey there, sorry this was two years ago and I really don't remember or use ayu either, I think this can be closed.
