### ISSUE TITLE
Stretched search icon (windows)

### ISSUE THREAD

**Issue by eriqamiqo** [dempfi/ayu#237]
![stretched-search](https://user-images.githubusercontent.com/1791899/76926617-c7794800-6917-11ea-8637-d93118197d40.png)

anyone having the same issue on windows devices?

**Comment by hypernova7** [comment]
I had the same problem, I just modified the `ayu.sublime-theme` file

**Comment by arnold-plxr** [comment]
I also had the same issue on my Macbook Pro macOS Big Sur.

Solution:
1. Open ayu.sublime-theme
2. Search for "input-search.png"
3. Below that there is "layer1.inner_margin", update the 2nd value from "0" to "30"
4. Save the file

<img width="613" alt="Screen Shot 2021-01-17 at 9 04 05 PM" src="https://user-images.githubusercontent.com/63797953/104843881-e49bf000-5907-11eb-8dd4-b4a11ad35368.png">

**Comment by eriqamiqo** [comment]
thanks @arnold-plxr 

tried it just a while ago and it works but aligns on top. made another tweak to align the search icon with the search text field. changed the `7` to `2` in `content_margin`

![image](https://user-images.githubusercontent.com/1791899/104988269-a232fa00-5a52-11eb-8f64-e48e1849a47b.png)

not sure if it's the same on Mac but I like the way it looks rn in my device after the adjustments.

again, thanks.
