### ISSUE TITLE
Ayu color schemes not listed via Schemr

### ISSUE THREAD

**Issue by MiguelDebruyne** [dempfi/ayu#238]
Hi there,

Just wanted you to know that the Ayu color schemes are not listed via the Schemr package although the themes do get listed in Themr. Schemr and Themr are good apps for switching between color themes and shemes. Could it be because the only way to properly activate the Ayu theme correctly is via the Ayu - activate command?

**Comment by dempfi** [comment]
Hmm, Schemr claims to support only ST 2 and 3. I've dropped support for those versions of Sublime. Using `ayu activate` command is the simplest way for now.
