### ISSUE TITLE
Optional dependency package 'A File Icon' no longer available

### ISSUE THREAD

**Issue by ghost** [dempfi/ayu#239]
When updating the package, the following message appeared:

> Package Control Messages
> ========================
> 
> ayu
> ---
> 
>   **ayu theme for Sublime Text**
>   https://github.com/dempfi/ayu/releases
>   
>   ---
>   
>   ayu from version 3.0.0 supports customization via A File Icon package
>   (https://github.com/ihodev/a-file-icon). Please install it for better expereince.
>   
>   ---
>   
>   # Version 5.1.0
>   
>   🎉 This release is all about contrast
>   
>   - Light theme UI and foreground contrast improvements
>   - Dark theme UI color contrast raised
>   
>   ---
>   
>   Breaking changes:
>   
>   - Removed UI font settings (`ui_font_size_small`, `ui_font_source_code_pro`, `ui_font_roboto_mono`)
>   
>   ---
>   
>   Version 5.0.3 contains a fix for the new block caret.

When navigating to https://github.com/ihodev/a-file-icon there does not seem to be a repository, nor does there seem to be a package which such name available.

Perhaps remove it from future Package Control Messages (and from the readme)?

**Comment by andreiborisov** [comment]
@pfwinfried it moved under Sublime Text organization due to abandonment by the original author:

https://packagecontrol.io/packages/A%20File%20Icon
https://github.com/SublimeText/AFileIcon
