### ISSUE TITLE
Plans for vim?

### ISSUE THREAD

**Issue by sobrinho** [dempfi/ayu#24]

**Comment by dempfi** [comment]
Not the vim, but neovim, yes, but not now, in near feature when I have more time.

**Comment by rafaelrinaldi** [comment]
@dempfi Let me know if you need help with that, I might be able to give it a shot. There are very few light themes that work well in Vim, it would be amazing to see ayu on that list 👍

**Comment by Leeiio** [comment]
+1

**Comment by sobrinho** [comment]
@rafaelrinaldi I think you should do it and make a pull request (can I pay you a beer?), then @dempfi could fine tune and etc! :)

**Comment by dempfi** [comment]
I tried to research what can be done and seems vim's has very limited syntax definition groups and all syntax highlighting plugins adding their own without any chance of compatibility with each other.

Anyway, result of my research is in screenshot below.
<img width="1680" alt="screen shot 2016-10-15 at 1 12 43 am" src="https://cloud.githubusercontent.com/assets/4568573/19404172/933ccdd2-9274-11e6-9178-ebdd31e17b9c.png">

**Comment by sobrinho** [comment]
Seems wonderful!

**Comment by sobrinho** [comment]
@dempfi can you attach it here or make a public branch to test that? 😬

**Comment by dempfi** [comment]
@sobrinho made a repo https://github.com/ayu-theme/ayu-vim. Note this is a rough implementation and a lot of things need to be added. And I'll appreciate any contribution - either opening an issues or filing PR.

**Comment by dempfi** [comment]
And let's move all discussions regarding the vim version to that repo.

**Comment by sobrinho** [comment]
Agreed, closing that one.

**Comment by rafaelrinaldi** [comment]
@dempfi @sobrinho Great stuff!
