### ISSUE TITLE
Support for Sublime Text 4

### ISSUE THREAD

**Issue by andreiborisov** [dempfi/ayu#240]
Sublime Text 4 dev builds are available via Sublime Discord server and it's slowly crawling to a wider dev release.

Since ayu is arguably the most well-thought-out theme for Sublime Text, it would be quite awesome to see ST4 supported eventually.

**Comment by dempfi** [comment]
Sublime text 4?! Amazing, I’ll check it out and try to support if it’s not hard.

**Comment by MelancholyAstronaut** [comment]
where is sublime 4?

**Comment by keithrussell42** [comment]
You can check out the Sublime Text Discord server. I _think_ this link should do it: https://discord.com/channels/280102180189634562/650695903446827011

I believe they have added features to the syntax stuff. Feel free to ask on the discord site. The devs are quite happy to help.

**Comment by kaiser101** [comment]
IMO its going to be some work, especially with the latest dev build 4092 and above. The menu bar has some breaking changes.

**Comment by deathaxe** [comment]
ST 4093+ adds a setting `themed_title_bar` which may be used by themes to switch between 
a) classical title bar and main menu and 
b) themed title bar with hamburger menu 

```
{
	"class": "title_bar",
    	"settings": ["themed_title_bar"],
    	"bg": "...",
	"fg": "...",
},
```

**Comment by kaiser101** [comment]
If I comment out the line 
            // "ui_native_titlebar",

I get the old menu back. So if we provide a flag to toggle this setting, I guess it might work.

**Comment by hsleewis** [comment]
Anyone knows what the right settings are for the latest ST4 4101 dev build? The titlebar now blends with the statusbar in the bottom :)

**Comment by deathaxe** [comment]
It's a core bug.

**Comment by hsleewis** [comment]
> It's a core bug.

Ah that explains a lot, it's temporary fixed when disabling and re-activating the theme. :)

**Comment by Jarvvski** [comment]
Was there any progress on this? :)

**Comment by desbest** [comment]
Is there any update on this? I would like to have the old menu bar work in the Ayu theme instead of having the menu button.

**Comment by dempfi** [comment]
I've started working on a new version here https://github.com/dempfi/ayu/pull/251. It all looks relatively easy, I just need to find a bit of time to finish

**Comment by dempfi** [comment]
Closed in https://github.com/dempfi/ayu/pull/251

**Comment by Jarvvski** [comment]
@dempfi what did the PR change exactly? Gotta say, I'd been using Ayu already for Sublime 4 for a few weeks now

**Comment by dempfi** [comment]
@Jarvvski the idea of this release was to support ST4 and improve the usability of the theme: 
- Updated tabs style to match ST 4 when separator lines are enabled and fixed broken styles;
- Refreshed all UI text colors for improved legibility;
- Updated editor colors to the latest version — nothing radical but legibility should be better;
- Added missing icons;
- Updated buttons;
- Updated tooltips;
- Updated selection both in the UI and in the editor;
- Decreased sidebar tree size;
- Decreased prominence of git indicators;
- Fixed broken highlights;
- Other things I can't recall off the top of my head.


I know 👆🏻 doesn't say much, but you can compare visually screenshots from [readme for the previous version](https://github.com/dempfi/ayu/blob/24476a8aae84468d03fa95181d0a01701925e88f/README.md#screenshots) and [the new readme](https://github.com/dempfi/ayu/blob/master/README.md#screenshots) to see what has changed.
