### ISSUE TITLE
HTML icons not loading in sidebar

### ISSUE THREAD

**Issue by pablocorbalann** [dempfi/ayu#241]
Hi, yesterday I downloaded your theme from the SublimeText 3 package control and I love it, it is really nice and it gives a different approach to Sublimetext.

I have only found a problem, ***the icon of the files with the HTML extension is not displayed in the side file bar***. I'm not sure if it's a bug on my device. I attach an image.

<img width="686" alt="ayuerror" src="https://user-images.githubusercontent.com/63709477/89593323-2439b880-d84f-11ea-9175-ea8c7599541a.PNG">

**Comment by dempfi** [comment]
Can't reproduce in the latest two releases. Most likely an issue on your side, @pablocorbalann
