### ISSUE TITLE
Please consider increasing contrast of function names in definitions

### ISSUE THREAD

**Issue by keithrussell42** [dempfi/ayu#242]
I've been finding it hard to see the names of functions in definitions. The colour is very close to the one used for keywords. It would be nice if the function names stood out more like the types do. It's also a bit tough since it seems to be the same as the method name in invocations. When I'm scanning through code I will tend to look for the function/method names. Yes, I know I can jump to any symbol but sometimes you just end up hitting PageDown a bunch or scrolling quickly. 

I'm talking here about the scope entity.name.function which is used in definitions for at least Java and Go:

func myFunctionName()

public void myFunctionName()

**Comment by dempfi** [comment]
Closed in https://github.com/dempfi/ayu/pull/251
