### ISSUE TITLE
quick documentation color in ayu dark is very dim

### ISSUE THREAD

**Issue by saiderflash** [dempfi/ayu#245]
It's hard to see in daylight. Please make quick documentation color more contrast.

**Comment by jingyuexing** [comment]
dark themes hurt your eyes,the background color is too dark

**Comment by saiderflash** [comment]
![InkedScreenshot 2020-12-24 223339_LI](https://user-images.githubusercontent.com/71758847/103098316-b42ea200-4638-11eb-8ce0-bc9bab788d53.jpg)

**Comment by saiderflash** [comment]
how can I increase this color contrast?

**Comment by dempfi** [comment]
Closed in https://github.com/dempfi/ayu/pull/251
