### ISSUE TITLE
Windows UI Invisible for Certain Themes

### ISSUE THREAD

**Issue by tayloraswift** [dempfi/ayu#252]
Dark Theme and Light Theme have nearly invisible UI on Windows for Minimise and Resize Buttons
![image](https://user-images.githubusercontent.com/58350457/132987186-86961c68-b432-4eb9-af7c-d31aac6b075b.png)
![image](https://user-images.githubusercontent.com/58350457/132987189-707b9d23-3e52-4d1d-9256-fcdbd4d8a223.png)
On hovering the Close button, it does light up red and is visible, but otherwise, blends in
![image](https://user-images.githubusercontent.com/58350457/132987199-dcae56b9-c380-4388-8bd2-48d47d0819bb.png)

**Comment by dempfi** [comment]
Thank you for the report @tayloraswift. I'll look into that, for now, you can enable native title bars via `"ui_native_titlebar": true` option

**Comment by dempfi** [comment]
There seems to be a bug in ST4 for Windows. For now, I've limited the scope of title bar adjustments on windows. Released the latest hotfix release.

**Comment by tayloraswift** [comment]
Thank you!!

**Comment by Baw-Appie** [comment]
@dempfi

When I changed the foreground color of the titlebar to #.000000, this issue was solved.
![image](https://user-images.githubusercontent.com/15670271/133871862-bef5256b-37eb-4ef6-9d7f-ad89057e9b88.png)
