### ISSUE TITLE
Spacing of quick panel items and auto-completions with `kind_info` needs some tweaks.

### ISSUE THREAD

**Issue by deathaxe** [dempfi/ayu#253]
There's just too much spacing between auto-completion items:

![grafik](https://user-images.githubusercontent.com/16542113/132998159-b74e42f4-9c0a-4fd5-9097-d39c9567cf2f.png)

Same for Goto Symbol:

![grafik](https://user-images.githubusercontent.com/16542113/132998179-8c5dd586-3e13-4062-86a8-a1b933d7dc60.png)

Normal item spacing needs to be set to 0 for all rows which contain `kind_info`. There are new elements to be used to control spacing instead.

**Comment by dempfi** [comment]
Thank you @deathaxe. I've adjusted for this new autocomplete behavior
