### ISSUE TITLE
ui_separator cause strange tab color in ST4

### ISSUE THREAD

**Issue by humiaozuzu** [dempfi/ayu#254]
when `ui_separator = false`
![image](https://user-images.githubusercontent.com/300016/133032390-0dd6eed1-1a4e-4df9-be1f-62d8ef45e9d2.png)

when `ui_separator = true`
![image](https://user-images.githubusercontent.com/300016/133032407-234cf3d2-b0ba-4012-8664-6928c34ec215.png)

**Comment by dempfi** [comment]
Which version of sublime do you use @humiaozuzu? Have you tried to restart sublime?

**Comment by humiaozuzu** [comment]
@dempfi  Sublime Text 4 (Build 4113) on macOS, I've tried restart and reinstall all plugins, still the same. 
Maybe I can install an old version of the plugin to test if any new commit has caused this problem?

**Comment by dempfi** [comment]
@humiaozuzu this might be caused by a faulty sublime cache. Clean reinstallation should help.
