### ISSUE TITLE
Color of URLs in package control lists

### ISSUE THREAD

**Issue by kevinvalk** [dempfi/ayu#255]
I thought that there already was an open ticket for this issue, but I cannot seem to find it.... Sorry if this is already being tracked.

In ayu dark and mirage the URLs in the package control lists (remove, install, etc) are hard to read:
![image](https://user-images.githubusercontent.com/3524694/133039409-a1939474-3d4c-4fe1-a12b-5f11322bd0f2.png)

**This is with version 6.0.0 of the ayu theme**

P.S. @dempfi thanks for the new releases 🥇!

**Comment by Aiq0** [comment]
See #243

**Comment by kevinvalk** [comment]
v6.0.3 has this implemented
![image](https://user-images.githubusercontent.com/3524694/134494923-ace9ff51-1ce5-46d4-a625-ab531bf7bbd1.png)
