### ISSUE TITLE
Broken themed title bar in v6 or v6.0.1 on Windows

### ISSUE THREAD

**Issue by princemaple** [dempfi/ayu#256]
![image](https://user-images.githubusercontent.com/1329716/133188174-f97317ef-be4a-4a0b-8176-68f138ee4bf7.png)

5.1 used to work properly and show title bar like above (screenshot taken with native adaptive theme)

6.0.1 somehow broke it.

![image](https://user-images.githubusercontent.com/1329716/133188330-5f28885c-373d-4d92-982a-e7bca639d32a.png)

**Comment by dempfi** [comment]
Hi @princemaple, there was a reproducible report of issues with custom title bar in windows https://github.com/dempfi/ayu/issues/252. It looked like an issue with the ST itself. Once resolved, this feature will be back.

**Comment by princemaple** [comment]
Hi, is there an issue on ST https://github.com/sublimehq/sublime_text to track with?

**Comment by dempfi** [comment]
Fixed in 6.0.2

**Comment by princemaple** [comment]
Thanks. I confirm that is fixed.
