### ISSUE TITLE
hamburger menu disappears in v6.0.x

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [dempfi/ayu#257]
Hello, 

i'm using sublime text 4 build 4107
i installed Ayu theme months ago, it works fine 
i had the hamburger menu like in this image: 
![133188174-f97317ef-be4a-4a0b-8176-68f138ee4bf7](https://user-images.githubusercontent.com/17873513/133471569-6d1db9c2-b186-4b3d-9916-dc6eb71a0b3c.png)

but these last days, Ayu did auto updates (probably to version 6.0.0 then 6.0.1) then a problem appears, 
the hamburger menu become to the old one like in this image: 
![ssss](https://user-images.githubusercontent.com/17873513/133472289-b3ab0a96-bc89-45d2-a57d-cf6d1316adb0.PNG)

`Note: i didn't update my sublime text, means the problem is from new Ayu version`

cordially

**Comment by dempfi** [comment]
Fixed in 6.0.2
