### ISSUE TITLE
v6.0.2 regression on sublime v3.2.2

### ISSUE THREAD

**Issue by rynop** [dempfi/ayu#259]
I still use Sublime v3.2.2 and ayu was installed via package manager.  

Recently the active tab no longer highlights the file name (white font in Mirage).  Gives this error:

```bash
Errors parsing theme:
  "settings" must be a vector in Packages/ayu/ayu-light.sublime-theme:464:15
```

Package manager must have auto-updated ayu to:

![image](https://user-images.githubusercontent.com/372730/134368591-895cbde0-06dd-48bb-b187-e356aef9b478.png)

If I manually install ayu v5.1.0 error goes away and things work again.

**Comment by dempfi** [comment]
Hi @rynop, I'm sorry to hear you have issues with ayu. Unfortunately, I had to drop support of ST 3 when upgrading ayu to ST 4 to have better focus. That said, I'll research whether it's possible to support ST 3 without much investment.

**Comment by rynop** [comment]
Totally understand. If it is not easy to dual support, maybe just a line in your readme install section stating that if you are Sublime v3 that manual install of Ayu v5.1.0 is required.  Will help save the next user some time (and you from not getting another issue reported)

**Comment by dempfi** [comment]
Great point, @rynop. There's [this](https://github.com/dempfi/ayu#sublime-text-3) in the readme for that.

**Comment by rynop** [comment]
Ah I didn't see that. Very sorry to waste your time here. Closing.
