### ISSUE TITLE
Tabs' text is getting cut off

### ISSUE THREAD

**Issue by udeyrishi** [dempfi/ayu#26]
The text in the tab bar is a little cut off:
<img width="222" alt="screen shot 2016-10-07 at 9 06 52 pm" src="https://cloud.githubusercontent.com/assets/4692593/19210270/1c21a746-8cd3-11e6-8331-da6e4c509f07.png">

**Comment by crapthings** [comment]
fix it pls!!!

this theme is super duper swag

**Comment by dempfi** [comment]
this is really a hard task accomplish because of `*sublime-theme` restrictions. but I'll try to fix if it's possible
