### ISSUE TITLE
ayu update 6.1.1 broke the line comment system

### ISSUE THREAD

**Issue by imskm** [dempfi/ayu#261]
When I wrote one line and pressed ctrl+/ (short curt to comment the current line) it commented the line as expected but when I pressed enter to create new line and pressed ctrl+/ without typing any character in new line then the previous commented line got uncommented. I repeated the same this many times to confirm that it's consistently doing same thing.
One more thing, when I wrote few words in second line and pressed the ctrl+/ then it worked fine.

I don't know it's feature or a bug.

**Comment by dempfi** [comment]
Hi @imskm, ayu can't affect the behavior of commenting/uncommenting. That seems like an issue with the sublime itself. Please report it to the https://github.com/sublimehq/sublime_text

**Comment by imskm** [comment]
> Hi @imskm, ayu can't affect the behavior of commenting/uncommenting. That seems like an issue with the sublime itself. Please report it to the https://github.com/sublimehq/sublime_text

Okay, my apology for this.
Today I opened up Sublime for work and got ayu theme upgrade message and after that I found that bug and I didn't think through and thought it's something with the ayu upgrade.

**Comment by dempfi** [comment]
no problem, @imskm
