### ISSUE TITLE
v6.1.1 Autohide taskbar doesn't work ST 4 (build 4113)

### ISSUE THREAD

**Issue by amritRaj789** [dempfi/ayu#262]
I am on windows 10 and I have set my taskbar to autohide.
When the sublime text window is in the foreground and completely maximized, my taskbar permanently hides and doesn't come back up when I hover my cursor near the bottom edge of the window.

Taskbar functions normally when I change my theme from Ayu to default sublime text theme.

**Comment by amritRaj789** [comment]
This seems like a ST4 problem [#4105](https://github.com/sublimehq/sublime_text/issues/4105). Some people pointed out that it happens with any theme which collapses the menu, and such themes are all extended from the Adaptive Theme.

**Comment by dempfi** [comment]
@amritRaj789 ayu provides an option to disable non-native title bars via `"ui_native_titlebar": true` setting. Please give it a try.

**Comment by amritRaj789** [comment]
@dempfi Thank you. I toggled the setting at the application level and it did solve the issue.
However, I would like to add that I am an absolute fan of the collapsed menu and would really want to have the minimalistic adaptive title bar without hampering the taskbar autohide.

**Comment by dempfi** [comment]
As you have found out it's not an issue with ayu but with the sublime. Once it's fixed there — all should work
