### ISSUE TITLE
Restore traditional menu on Windows

### ISSUE THREAD

**Issue by fburleigh** [dempfi/ayu#263]
Facts: Sublime 4, latest Ayu (thank you for effort!).

Hello. For a brief moment with Ayu I had a traditional Windows menu -- across the app's top. I prefer that. And then the tri-bar "hamburger" returned. I gather by searching that my preferred approach is considered a bug.

Is there a setting I could use to restore the horizontal menu I prefer?

I promise, I made a good-faith effort to find something in the theme's settings. But without documentation, I'd be guessing. ;-)

Thank you.

**Comment by dempfi** [comment]
Hi @fburleigh, there's a setting for that. You can set "ui_native_titlebar" to true and it should bring back classic windows menubar.

**Comment by fburleigh** [comment]
@dempfi, thank you. For reference for other users who would like the same behavior, I added:

`"ui_native_titlebar": true`

to my Sublime Preferences then saved that file. Sublime reacted immediately and correctly.
