### ISSUE TITLE
Unreadable tab label under Linux HiDPI

### ISSUE THREAD

**Issue by luislavena** [dempfi/ayu#29]
Hello,

Thank you for creating this theme! I've been enjoying it a lot since installed!

It seems that recently there has been an update that is affecting how tab labels are rendered. I've only tested Linux (Ubuntu) with a HiDPI screen:

![screenshot from 2016-10-08 14-49-38](https://cloud.githubusercontent.com/assets/4182/19214955/fe36658e-8d66-11e6-9ca7-033c87c6c8ba.png)

Both active an inactive tabs shows the same issue.

This might be related to #28 since was working yesterday without issues.

- Sublime Text 3, Dev Channel build 3125
- Ubuntu GNOME 15.10 x64
- Roboto Mono font installed

Settings:

```json
{
	"color_scheme": "Packages/ayu/ayu.tmTheme",
	"theme": "ayu.sublime-theme"
}
```

Let me know any other information that might help out debugging this issue.

Thank you
:heart: :heart: :heart:

**Comment by 314r** [comment]
Same problem here with a 22" screen, 1680 x 1050, under Fedora 23, Roboto Mono font installed, Sublime 3126.

Thank you for this theme !

**Comment by lyftmika** [comment]
Same on Windows. Sublime 3126

**Comment by Metal-Mighty** [comment]
Same on Windows with build 3126. 15" with 1920x1080 res, Roboto Mono font installed.

![upload 31](https://cloud.githubusercontent.com/assets/5247527/19215393/ba9b187a-8d6a-11e6-8ac8-7ad39745b517.png)

**Comment by renkawan** [comment]
Same on mine, Win 10 with 1366x768 res, and Roboto Mono font installed. Please help, thanks
![sublime_ayu](https://cloud.githubusercontent.com/assets/1291936/19215626/0d102c78-8dcd-11e6-827a-24457e66bde2.PNG)

**Comment by dempfi** [comment]
shit, behavior of sublime text Is something unpredictable across platforms :( I'll rollback latest update release right away

**Comment by dempfi** [comment]
released 1.3.1, soon package control should update `ayu`, sorry for this error. will try to test next time on each platform

**Comment by Metal-Mighty** [comment]
Package Control has updated ayu, text back to normal. Thanks!

**Comment by renkawan** [comment]
well done, thanks guys!

**Comment by 314r** [comment]
Thanks !

**Comment by chiotis** [comment]
Well done. Problem fixed in Win10 Sublime3

**Comment by luislavena** [comment]
Thank you @dempfi for the promptly response and the solution! :heart: :heart: :heart_eyes_cat:

**Comment by ClementParis016** [comment]
I am experiencing the same issue on Windows 10 using the latest theme's version:

![image](https://cloud.githubusercontent.com/assets/5601687/20032217/e411f51c-a385-11e6-9091-f1c7e7f40cfe.png)

**Comment by luislavena** [comment]
@ClementParis016 set `ui_fix_tab_labels` to `true`: https://github.com/dempfi/ayu#settings
