### ISSUE TITLE
Tab padding

### ISSUE THREAD

**Issue by ridjis** [dempfi/ayu#33]
Can you add property like "ui_separator" for bigger tabs (tabs with bigger padding)?

**Comment by dempfi** [comment]
Hi @ridjis, how bigger? I mean do you have any expectations?

**Comment by ridjis** [comment]
@dempfi Like in material or brogrammer theme.

**Comment by shaylash** [comment]
Hi and first of all thanks a lot for your work!!
Yes it would be nice to add more padding on tabs. Because the file name if truncated even with ui_font_size_small set to true. Keep us posted and by the way super nice theme.

**Comment by dempfi** [comment]
@ridjis done in https://github.com/dempfi/ayu/releases/tag/1.3.2. @shaylash this change will not fix the issue with cut tab labels. still trying to figure out best way to handle that.

**Comment by omento** [comment]
So far I've been able to remedy the cut-off text by setting the `tab_label` font-size to 10 using PRV. Unfortunately, I do not know if there is a true fix for this. An hour of googling has shown this issue dating back to about 2013, with no proper solution. A theme I still use along with Ayu is Agila, and the tabs aren't cut off text-wise, but they are using a different font family set to 11.5 for size.

**Comment by dempfi** [comment]
@omento I have a working fix for macOS version with Roboto or almost any other font, but not for Linux and Win versions

**Comment by omento** [comment]
@dempfi That's great to hear! I wonder what could be causing the mixup for the other operating systems.

**Comment by dempfi** [comment]
@omento another bug in sublime making fully transparent rgba colors to be rendered as black

**Comment by dempfi** [comment]
https://github.com/dempfi/ayu/pull/53
