### ISSUE TITLE
How to hidden the title bar at the top?

### ISSUE THREAD

**Issue by hzb** [dempfi/ayu#38]
![screen shot 2016-10-12 at 10 50 44](https://cloud.githubusercontent.com/assets/535675/19295861/f9232c20-9069-11e6-8087-8f311a45a68f.png)

How to hidden or remove the title bar at the top above?  My settings->user

```
{
	"color_scheme": "Packages/ayu/ayu-light.tmTheme",
	"font_face": "Andale Mono",
	"font_size": 15,
	"theme": "ayu-light.sublime-theme"
}
```

Thanks.

**Comment by dempfi** [comment]
Seems I need to change screenshots or add note :D. See https://github.com/dempfi/ayu/issues/8.
