### ISSUE TITLE
Sidebar Label Margin Error

### ISSUE THREAD

**Issue by omento** [dempfi/ayu#4]
First off: amazing theme! Really nice and clean.

I found after installing Ayu today that in the sidebar, the "Open Files" label at the top was being cut off, as if there was a negative margin. using PRV I went into the themes options, and in both ayu.sublime-theme and ayu-light.sublime-theme and found the setting for this on line 515 and 522:

`"content_margin": [0, -10, 0, 0],`

After setting the -10 to 0 or 10, the label behaved as predicted and wasn't getting cut off. I wasn't sure if this was a by design setting or a behavior based off of the system you're working on.

A different default color besides straight black for the sidebar labels would also be a suggestion for the dark theme.

**Comment by dempfi** [comment]
thanks @omento, glad you like it. regarding the issue. yeah, that happened because of my setup, I never used open files list in sidebar so missed to check with that option too. will fix soon

**Comment by dempfi** [comment]
Same issue here https://github.com/dempfi/ayu/issues/17. @omento can you please confirm that you're on linux version too and provide version of ST. In general these labales(`Open Files` and `FOLDERS`) should be hidden, but they aren't. Let me investigate a bit more.

**Comment by omento** [comment]
I can confirm I'm on Windows. Specifically Windows 10 Build 1607. I usually choose to display the sidebar, in contrast to its default hidden state.

**Comment by idrum4316** [comment]
![folders-clipped](https://cloud.githubusercontent.com/assets/2634334/19370189/d4cc1dbc-916f-11e6-8087-20a5544c8717.png)

I'm on Ubuntu 16.10, and I think I'm seeing the same thing with the FOLDERS label.

**Comment by dempfi** [comment]
Fixed in https://github.com/dempfi/ayu/pull/53
