### ISSUE TITLE
Top tabs padding issue

### ISSUE THREAD

**Issue by sobolevn** [dempfi/ayu#40]
First of all, this theme is so good!

But I have a little issue. 
I am working with
- macOS X 
- Sublime3
- ayu v1.3.1

Screenshots:
<img width="142" alt="2016-10-14 0 09 59" src="https://cloud.githubusercontent.com/assets/4660275/19367235/f395e768-91a2-11e6-8a30-953d9761fe56.png">
<img width="141" alt="2016-10-14 0 09 25" src="https://cloud.githubusercontent.com/assets/4660275/19367234/f3957ff8-91a2-11e6-839d-300288845601.png">

**Comment by dempfi** [comment]
Hi @sobolevn, I know about this issue and even tried to fix, but the fix caused more issue :D check this https://github.com/dempfi/ayu/issues/29. still wondering how to fix this since sublime tab label has hardcoded height not any font can fit there without being cut of.

**Comment by mert-celen** [comment]
<img width="412" alt="issue" src="https://cloud.githubusercontent.com/assets/9132682/19369549/0a41c586-919e-11e6-9065-495894ef1786.png">
I can confirm it's happening in El Capitan as well.
@dempfi I hope you can fix that, I seriously love this theme, thank you for your hard work.

**Comment by sobolevn** [comment]
Just want to report that it still happens with the latest version (`1.3.3`)  with the `"ui_big_tabs": true` option set.
<img width="450" alt="2016-10-16 19 58 49" src="https://cloud.githubusercontent.com/assets/4660275/19419259/7adfe74c-93dc-11e6-8284-7418a70d265d.png">

**Comment by dempfi** [comment]
https://github.com/dempfi/ayu/pull/53
