### ISSUE TITLE
"New folder" tab is overflowed

### ISSUE THREAD

**Issue by sobolevn** [dempfi/ayu#42]
I am using:
- macOS X
- Sublime3
- ayu v1.3.1

Settings:
```json
	"color_scheme": "Packages/ayu/ayu.tmTheme",
	"font_size": 16,
	"theme": "ayu.sublime-theme",
	"ui_font_size_small": false,
	"ui_separator": false
```

I have also `git` plugin installed.

Here's the screenshot:
![2016-10-14 21 35 00](https://cloud.githubusercontent.com/assets/4660275/19398701/937f3b5e-9256-11e6-8ecb-8189b54c7b73.png)
![2016-10-14 20 45 02](https://cloud.githubusercontent.com/assets/4660275/19398702/9383c034-9256-11e6-96d8-34cae02cd1d6.png)

**Comment by dempfi** [comment]
here the solution https://github.com/dempfi/ayu/issues/12#issuecomment-251897721
