### ISSUE TITLE
python code color

### ISSUE THREAD

**Issue by sobolevn** [dempfi/ayu#43]
Is it supposed to be like so? I mean that the code is yellow.
<img width="390" alt="2016-10-15 11 28 27" src="https://cloud.githubusercontent.com/assets/4660275/19408634/07a33732-92cb-11e6-847c-118bbee19da9.png">

It is a code inside a function:

``` python
@app.route('/', methods=['POST', 'GET'])
def home():
    if request.method == 'POST':
        form = AdvertResponseForm(request.form)

        if form.validate():
            advert_response = AdvertResponse()
            form.populate_obj(advert_response)
            db.session.add(advert_response)
            db.session.commit()
```

**Comment by dempfi** [comment]
@sobolevn this is a bug, I need to adjust a theme colors for python class methods. will fix in one of next releases

**Comment by Mattiaslndstrm** [comment]
Thank you for an amazing theme!

Is this the same bug that makes the methods the same color as the variables? It's the only problem I have with this theme.

<img width="383" alt="screen shot 2017-03-09 at 15 19 01" src="https://cloud.githubusercontent.com/assets/13505830/23775154/d53e94d2-04ec-11e7-9bf5-bf12284dcae4.png">

**Comment by dempfi** [comment]
hey guys, sorry it took so long, but this issue is finally fixed in https://github.com/dempfi/ayu/releases/tag/3.1.0 :)
