### ISSUE TITLE
Tab label padding & sidebar layout.

### ISSUE THREAD

**Issue by tdjsnelling** [dempfi/ayu#45]
Love this theme, particularly the light version.
Just a couple of minor issues:
- Label text on tabs is slightly too large, so certain letters get cut off.
  ![7c5aa0cfae4b8f0acf87080d97715094](https://cloud.githubusercontent.com/assets/6264509/19410970/4078cb24-92f0-11e6-8be1-54252190500d.png)
- In the sidebar, the headings are not styled and the 'Open Files' heading is overlapped by the File/Edit bar above.
  ![1b20ca31471f91c4c366ac34bba22665](https://cloud.githubusercontent.com/assets/6264509/19410981/64a59fd6-92f0-11e6-9796-437631964f4c.png)

Apart from that, the theme is perfect!

**Comment by dempfi** [comment]
Hi @tdjsnelling, what versions of ST and OS do you use?

**Comment by tdjsnelling** [comment]
Sublime Text 3 build 3126 on Windows 10.

**Comment by dempfi** [comment]
Thank you very much for that info. I tried on windows 10 with all latest updates and same version of ST and wasn't able to reproduce. I suppose it may be connected with hardware or more possibly and easier to fix with other packages. @tdjsnelling can you please attach you paxkage control user settings file. It contains info about all installed packages.

Location of that config is: `Preferences -> Package Settings -> Package Control -> Settings - User`

**Comment by tdjsnelling** [comment]
@dempfi here is the contents of my package control settings file.
`{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"AutoHotkey",
		"ayu",
		"Package Control",
		"PackageResourceViewer",
		"PowerShell",
		"Print to HTML"
	]
}
`

**Comment by omento** [comment]
@tdjsnelling A quick fix can be found in my post in #4 if you use PRV. It's two numbers that cause the issue.

**Comment by tdjsnelling** [comment]
@omento nice one, that's fixed it.
I also changed the heading style to fit with the theme:
`{
    "class": "sidebar_heading",
    "color": [130, 142, 153],
    "font.face": "Roboto mono",
    "font.size": 12
  },
`
![36b15dc8a1d8ae0480eb729685a38b3b](https://cloud.githubusercontent.com/assets/6264509/19452898/b75f1228-94aa-11e6-9856-cbbf4383e910.png)

**Comment by dempfi** [comment]
Fixed in https://github.com/dempfi/ayu/pull/53

**Comment by matteocontrini** [comment]
Was the fix released? I'm still experiencing this issue...
