### ISSUE TITLE
Parens of function calls with arguments looks different then without arguments in JavaScript (Babel)

### ISSUE THREAD

**Issue by k15a** [dempfi/ayu#52]
They should have probably the same color. 🤔

![Difference](https://cloud.githubusercontent.com/assets/20357450/19686581/0b41f744-9ac2-11e6-9308-4d10f316ca74.jpg)

**Comment by dempfi** [comment]
I do think this should be addressed to developer of syntax highlighter because in ayu I've add only one specific rule for js to have different colors for ES next features such as decorators.
