### ISSUE TITLE
Tab Text is Illegible

### ISSUE THREAD

**Issue by ryanjmclaughlin** [dempfi/ayu#56]
I am on Win10, the tab text is very faint and with the 2.0 upgrade almost looks like a drop shadow is being applied...

![image](https://cloud.githubusercontent.com/assets/212216/20011826/45cdeab2-a283-11e6-916d-9452c4ec836b.png)

**Comment by dempfi** [comment]
It's a problem of sublime on windows, use `ui_fix_tab_labels` option as it states in README.

**Comment by schnittstabil** [comment]
I'm using Linux (Debian), same problem, same solution.
