### ISSUE TITLE
Theme labels text error

### ISSUE THREAD

**Issue by omento** [dempfi/ayu#57]
With the release of Ayu 2.0, the theme labels (not scheme) are all messed up. The screenshots below demonstrates what I've been able to reproduce on Windows 10 and CentOS 7. Also, did you remove the labels from the sidebar (by matching the color to the background)?

![ayu-dark](https://cloud.githubusercontent.com/assets/14795448/20040145/fa8522b6-a41f-11e6-82aa-c9f6921c465b.png)
![ayu-light](https://cloud.githubusercontent.com/assets/14795448/20040146/fdfbb91e-a41f-11e6-98b8-fd9bd671aca7.png)
![ayu-mirage](https://cloud.githubusercontent.com/assets/14795448/20040147/ff4f2b34-a41f-11e6-8240-34719d0b2367.png)

Sidenote: Coming from Agila, the Ayu-Mirage theme is much appreciated!

**Comment by dempfi** [comment]
Hi @omento, for tab labels add ```json 
"ui_fix_tab_labels":  true  // to fix tab labels if they look not right
``` as it states in readme. Don't know what's wrong with light theme, will take a look today.

Yes I set color of sidebar headings to match with background to hide them.

**Comment by omento** [comment]
@dempfi Thanks for the update! I probably should have taken a better look through the README with a 2.0 release ;) That fixed it.

Was the cut off text in the page tab labels ever fixed? No worries if it's not, but I'm still get letters that go below the character line get cut off.

**Comment by dempfi** [comment]
@omento there were fixed in 2.0 but for some Linux and Windows machines it doesn't work properly, like in you screenshots. And the option you used to fix that problem is actually enables old behavior with cut text.

**Comment by dempfi** [comment]
@omento I will add support for other fonts with better line height so cut text will not be an issue for anyone.

**Comment by dempfi** [comment]
this should be fixed in latest release of ST3 and ayu. Feel free to reopen if it isn't
