### ISSUE TITLE
Files not found after Upgrade

### ISSUE THREAD

**Issue by OrkoHunter** [dempfi/ayu#59]
Sublime revoked my color scheme saying that `.tmTheme` and `.sublime-theme` files not found after the Package was upgraded.

**Comment by dempfi** [comment]
Hi @OrkoHunter, you have to change ayu dark declaration in you settings to
```json
"theme": "ayu-dark.sublime-theme",
"color_scheme": "Packages/ayu/ayu-dark.tmTheme",
```

**Comment by OrkoHunter** [comment]
That worked, thank you. :)
But the tabs look weird.
![screenshot_2016-11-09_16-08-22](https://cloud.githubusercontent.com/assets/8065913/20135659/e563b702-a696-11e6-879d-e0e91a1338ab.png)

**Comment by dempfi** [comment]
@OrkoHunter add this 
```json
"ui_fix_tab_labels":  true  // to fix tab labels if they look not right
```
btw all this info were shown to you when Package Control updated the Theme and all this info is available in README of this repository.

**Comment by OrkoHunter** [comment]
Thank you.
