### ISSUE TITLE
wrong graphic with advanced new file plugin

### ISSUE THREAD

**Issue by crapthings** [dempfi/ayu#62]
it looks like statusbar cut the advnaced new file input box

<img width="1918" alt="screen shot 2016-11-14 at 10 34 04" src="https://cloud.githubusercontent.com/assets/1147704/20251657/ea51f662-aa55-11e6-9fa9-8d58f166994a.png">

**Comment by dempfi** [comment]
Duplicate of https://github.com/dempfi/ayu/issues/12

**Comment by crapthings** [comment]
cool~
