### ISSUE TITLE
Ayu for Ace Editor

### ISSUE THREAD

**Issue by k15a** [dempfi/ayu#63]
Hey,

I just published the color scheme for ace. Hope that's ok for you? Would you mind taking a look if all the licensing stuff is ok for you? I've included your license in the light.js, mirage.js and dark.js files.

https://github.com/k15a/ayu-ace

**Comment by dempfi** [comment]
wow, this is so fucking awesome. thank you very much @k15a for spreading the word 👍 

Actually if you think it will ok for you, I can add you as contributor to https://github.com/ayu-theme org and you can move the repo to that organization. WDYT?

**Comment by k15a** [comment]
Yeah that would be great 👍

**Comment by dempfi** [comment]
I sent an invitation. Welcome onboard :)
