### ISSUE TITLE
Emphasize some keywords

### ISSUE THREAD

**Issue by k15a** [dempfi/ayu#67]
Yesterday I showed a friend of mine your color theme. He said that it looks beautiful but he misses some diversity of keywords.
I thought it would be great if for example the attributes in HTML and JSX would be italic and in Markdown _`_italic_`_ and __`__bold__`__ would be actually bold and italic.

What are your thoughts?

**Comment by dempfi** [comment]
hey man, good catch, I'll try to add this is next version along with bug fixes

**Comment by dempfi** [comment]
done in https://github.com/dempfi/ayu/releases/tag/3.1.0
