### ISSUE TITLE
Option show_tab_close_buttons ignored if file not saved

### ISSUE THREAD

**Issue by yckart** [dempfi/ayu#68]
If the Sublime Text setting `show_tab_close_buttons` is set to `false`, ayu still shows a close button on tabs that are unsaved and not empty.

![ayu-show_tab_close_buttons](https://cloud.githubusercontent.com/assets/529130/20467142/40d10b92-af81-11e6-8865-1d568b796062.png)

- macOS Sierra 10.12.1 (16B2657)
- Sublime Text 3126

**Comment by dempfi** [comment]
hi @yckart, this is a indicator for "dirty" state of file

**Comment by dempfi** [comment]
@yckart you're welcome to open a PR and resolve the issue with `highlight_modified_tabs: false` in case if I don't fix it in next version.

about indicator/button: I like the current behavior more. `ayu` is released under MIT license so feel free to fork and change the indicator

**Comment by dempfi** [comment]
closed in 2.0.3
