### ISSUE TITLE
Square tabs doesn't work?

### ISSUE THREAD

**Issue by Endorphinex** [dempfi/ayu#70]
Square tabs and this whole modern UI shown in screenshots, doesn't work for me. [Here](http://screenshot.sh/mE8nzldO1rcYN) you can see it.
Do I have something messed up in [my config](http://screenshot.sh/oeYqO9u4XLGsp), or I just don't know how to set something?

**Comment by dempfi** [comment]
You missed to add `theme` entry as it's shown in https://github.com/dempfi/ayu#activation
