### ISSUE TITLE
Please replacing the console icon on the status bar

### ISSUE THREAD

**Issue by breeze-liu** [dempfi/ayu#71]
thank you to share this theme, it's very amazing & beautiful to me, except this icon 
<img width="73" alt="2016-11-27 3 09 47" src="https://cloud.githubusercontent.com/assets/13219988/20646455/aa86ee08-b4b3-11e6-9ccf-52d0236731af.png">

could you fix it?

**Comment by dempfi** [comment]
Hi, @breeze-liu will fix soon

**Comment by breeze-liu** [comment]
thank you!

**Comment by dempfi** [comment]
closed in 2.0.3
