### ISSUE TITLE
Veiw -> Side Bar -> Show Open Files 

### ISSUE THREAD

**Issue by motorguo** [dempfi/ayu#74]
hello!
There are bugs, Line height too high.

`Veiw -> Side Bar -> Show Open Files `

#### Settings
```
{
    "color_scheme": "Packages/ayu/ayu-mirage.tmTheme",
    "font_face": "Roboto Mono",
    "font_size": 10,
    "theme": "ayu-mirage.sublime-theme",
    "ui_big_tabs": true,
    "ui_fix_tab_labels": true,
    "ui_separator": true
}
```

**Comment by dempfi** [comment]
Can you please attach a a Screenshot?

**Comment by motorguo** [comment]
Thanks, Is the result of the previous theme.
but,  Seems less `OPEN FILES` and  `FOLDERS`.

![fv4wii5mw 2x5_3a1g 21o](https://cloud.githubusercontent.com/assets/16831715/20857628/fbe832ee-b96c-11e6-9295-9893f77c2cbd.png)

Just some advice.

**Comment by motorguo** [comment]
And here, seems to be some problems.

![mec z 5d3iek kohx n n7](https://cloud.githubusercontent.com/assets/16831715/20857656/a02cb514-b96d-11e6-8c4a-9f45ee7db152.png)

![a9nj jbrcoq hw o3l ut](https://cloud.githubusercontent.com/assets/16831715/20857658/a613a99c-b96d-11e6-9eaa-27aacfcceaf5.png)

**Comment by motorguo** [comment]
In `Microsoft Windows [ver 10.0.14393]` 
No matter which font. Can not achieve the effect of drawing.

![-1](https://cloud.githubusercontent.com/assets/16831715/20857787/3baf0d68-b971-11e6-938a-5821ed486d00.jpg)

**Comment by dempfi** [comment]
@motorguo regarding the first screenshot. it's intended behavior. I just don't like this labels. but any PR which will add a setting for showing them is welcome.

second one is really complicated. I will try to somehow fix it in next version

**Comment by motorguo** [comment]
Thank you for your reply.
