### ISSUE TITLE
Make Scroll bar thick

### ISSUE THREAD

**Issue by prog-rajkamal** [dempfi/ayu#75]
Ayu theme uses very thin scroll bar, making it harder to use. 

For files, we can easily use map bar for vertical scrolling. But for horizontal scrolling, there is no way out.

I suggest to have thick scoll bar (by default) and add option for thin scroll bar for user to customize

**Comment by dempfi** [comment]
Hi @prog-rajkamal, yeah, will definitely add this feature

**Comment by dempfi** [comment]
closed in https://github.com/dempfi/ayu/releases/tag/2.1.0
