### ISSUE TITLE
Clicking an arrow in the sidebar opens the parent folder

### ISSUE THREAD

**Issue by rsynnest** [dempfi/ayu#76]
Clicking on the arrows in the directory in the sidebar opens the parent folder.
GIF for reference:

![out-1-iloveimg-cropped](https://cloud.githubusercontent.com/assets/4392850/20993154/42cbdc28-bc9d-11e6-8e68-e3bc8a1db97d.gif)

**Comment by dempfi** [comment]
hi @rsynnest can you please provide version of ST?

**Comment by mert-celen** [comment]
@dempfi I have exact same problem in OS X 10.11.6
Sublime Version : Build 3126

**Comment by rsynnest** [comment]
Version info:
`Sublime Text 3: Stable Channel, Build 3126`
`Debian 3.16.0-4-amd64`

**Comment by dempfi** [comment]
@rsynnest and @mert-celen seems you've installed UI theme fro ST2 not ST3. can you please check if your settings match https://github.com/dempfi/ayu#sublime-text-3

**Comment by mert-celen** [comment]
@dempfi you are absolutely right, correcting lines solved issue. I forgot the change lines after I updated sublime to 3.

**Comment by rsynnest** [comment]
Ah, thank you! My mistake.
