### ISSUE TITLE
Ugly fonts in tabs

### ISSUE THREAD

**Issue by sarneeh** [dempfi/ayu#78]
Hey!

I've just installed the ayu theme to Sublime Text 3 and it looks gorgeous! Except one thing... Fonts in the tabs are looking really ugly and hard to read. Did someone have similar problem, do you have a fix for it, or did i just found a bug?

More info:
OS: Windows 10 64Bit
Sublime: ST3 64bit Build 3126

Here's how it looks like:
![Ugly font](https://i.imgur.com/vMS7KI8.png)

And yes, i did install the Roboto Mono font.

**Comment by k15a** [comment]
Take a look here: https://github.com/dempfi/ayu/blob/master/README.md#settings

**Comment by sarneeh** [comment]
@k15a Oh, damn... I'm blind! Sorry, i didn't notice that. Thanks a lot, it works! :)
