### ISSUE TITLE
Hide macOS Top Bar

### ISSUE THREAD

**Issue by martinwolf** [dempfi/ayu#8]
Hey,

in you screenshots (https://camo.githubusercontent.com/fb5f7fda1b259389eff3674449772fee34a5af5f/687474703a2f2f692e696d6775722e636f6d2f30434c493344482e706e67) there is no macOS window top bar. Are these screenshots faked or is there a way to hide this top window bar?

Thank you,
Martin

**Comment by dempfi** [comment]
Hey guys. I just cut off the window title bars because I hate them. There is no way to hide title bar however there is tool to adjust it http://flavours.interacto.net.

**Comment by martinwolf** [comment]
Okay, that's what I thought. Is kinda missleading tho because the theme looks much more modern in the photoshopped screenshot because the whole app looks more moder. But you know that, I guess. 😀 

Anyway, good work with the theme! 👍 

Cheers,
Martin
