### ISSUE TITLE
there are some problems on sublimt3 (Mac sublime3 v3126)

### ISSUE THREAD

**Issue by chenweihan** [dempfi/ayu#81]
Hi:
there are some problems use 2 theme on sublimt3 (Mac sublime3 v3126). when click the icon , the function has a problem  and rename have some layout problems.
![g1](https://cloud.githubusercontent.com/assets/1927864/21298891/11559f02-c5d1-11e6-9901-32de82752d22.png)
![g2](https://cloud.githubusercontent.com/assets/1927864/21298903/2b46670c-c5d1-11e6-8dfd-f068234f1493.png)

**Comment by k15a** [comment]
Related to #12
