### ISSUE TITLE
Increase contrast of inactive labels

### ISSUE THREAD

**Issue by bfred-it** [dempfi/ayu#84]
The text contrast in inactive tabs, inactive sidebar and the command panel is [extremely low](https://leaverou.github.io/contrast-ratio/#%233c4b5a-on-%23141920). 

<img width="574" alt="screen shot 2016-12-23 at 17 02 00" src="https://cloud.githubusercontent.com/assets/1402241/21449590/a20db6ea-c8a3-11e6-9c0c-9e1bcff73cbe.png">
<img width="187" alt="screen shot 2016-12-23 at 17 01 47" src="https://cloud.githubusercontent.com/assets/1402241/21449591/a213d87c-c8a3-11e6-8917-9360c4f67494.png">

I understand that this is done as to simulate some "focus mode" where the main code is visible and the rest is, but as is it's a bit hard to use.

Is it possible to have an option to increase the contrast?

**Comment by dempfi** [comment]
Hi @bfred-it that's the problem/benefit of dark theme, you can use mirage which has better contrast and optimized for work in dark room, while dark theme is isn't

**Comment by bfred-it** [comment]
True, it's slightly better, but not very much so: https://leaverou.github.io/contrast-ratio/#%235f7080-on-%23272c3a

**Comment by dempfi** [comment]
hm you have a point. Will check out what I can improve.

**Comment by geordee** [comment]
It's difficult to see the selection in matte screens. The dark theme is good, and mirage looks a bit washed out.

**Comment by dempfi** [comment]
Done in last release

**Comment by bfred-it** [comment]
Thank you @dempfi!
