### ISSUE TITLE
emoji bug

### ISSUE THREAD

**Issue by cjahv** [dempfi/ayu#85]
![image](https://cloud.githubusercontent.com/assets/15372793/21492563/d3330874-cc40-11e6-81a0-9ccbcc37ff69.png)

**Comment by k15a** [comment]
AFAIK this is a bug with sublime.

**Comment by dempfi** [comment]
hi @cjahv not sure if I can do something with it, as @k15a mention this seems to be a bug with sublime. But I'lll take a look if it possible to adjust emoji's colors
