### ISSUE TITLE
show_input_panel panel height error

### ISSUE THREAD

**Issue by easyfrog** [dempfi/ayu#88]
When use custom plugin use 
`self.window.show_input_panel('commands:',self.lastInput,self.on_done,self.on_update,self.on_cancel)`.

the panel height is to small.  seems like hide by status bar.

<img width="558" alt="panel" src="https://cloud.githubusercontent.com/assets/10724325/21608026/e4e9b130-d1f4-11e6-84dd-4a674db2f926.png">

**Comment by k15a** [comment]
Look at #12
