### ISSUE TITLE
Sidebar enhancement field gets cut by the bottom bar

### ISSUE THREAD

**Issue by alexcanessa** [dempfi/ayu#89]
When I try to rename or move a file through Sidebar Enhancement, the text field gets chopped.

![image](https://cloud.githubusercontent.com/assets/1176495/21926227/c197b336-d978-11e6-9a5e-b60f92b9ae46.png)

**Comment by k15a** [comment]
Duplicate #12

**Comment by alexcanessa** [comment]
Thank you @k15a
