### ISSUE TITLE
Problems with latest macOS sierra BETA + Sublime DEV channel

### ISSUE THREAD

**Issue by frank-laemmer** [dempfi/ayu#9]
sorry to bother, have some problems installing the theme. 

* Sublime: 3125
* macOS: 16B2338c

what it looks like when activating:

<img width="355" alt="screen shot 2016-10-05 at 15 59 09" src="https://cloud.githubusercontent.com/assets/962736/19116205/ee6f1898-8b14-11e6-95a2-51a9f0852b9e.png">

from the console:
```
error: Error loading colour scheme Packages/ayu/widgets/Widget - ayu.stTheme: Unable to open Packages/ayu/widgets/Widget - ayu.stTheme
```

maybe it's my mistake? Sublime configuration?

**Comment by dempfi** [comment]
Hey @frank-laemmer, not bothering at all, I'm glad to help. 

Regarding the issue, I'm on 3126 and haven't seen this issue so, can you please tell me how you installed the theme, from package control or manually, the latest release?

Also, have you restarted sublime after activation?

**Comment by frank-laemmer** [comment]
installed it manually —  as package control is [ignored with the current version](https://forum.sublimetext.com/t/upgrade-to-3124-caused-package-control-to-move-into-ignored-packages/23080/2). maybe helpful: [this martial theme](http://equinsuocha.io/material-theme/) fails the same way. yes, tried it multiple times, also restarted sublime.

again, mind it's also the latest macOS beta (released yesterday). maybe something about custom title bar — and also maybe i screwed up something in my config …

nevermind this. I can life without, maybe this helps in the future, maybe it fixes with an update.

**Comment by pzgz** [comment]
I am with excatly same versions of macOS and sublimetext, the theme is working fine on my box, I installed it through package control.

**Comment by dempfi** [comment]
@frank-laemmer I believe you missed to rename direactoy to `ayu`

**Comment by frank-laemmer** [comment]
YES. indeed that was the case. I feel sooooo stupid. Please close and delete this issue from the internet forever.
