### ISSUE TITLE
Tabs shadows issue 

### ISSUE THREAD

**Issue by herrjemand** [dempfi/ayu#90]
Hey. Thanks for the theme. I am experiencing issues with shadows in tabs. It's very hard to see text clearly as shadows tend to blend text with background.

![_189](https://cloud.githubusercontent.com/assets/1636116/21959628/8aeb12d2-db31-11e6-969e-abe88a138cb3.png)

Same issue on Linux and Windows.

**Comment by k15a** [comment]
You have to set `ui_fix_tab_labels` to  `true` in your settings.

https://github.com/dempfi/ayu/blob/master/README.md#settings

**Comment by herrjemand** [comment]
@k15a 
YOU
ARE
AWESOME!
:beers:
