### ISSUE TITLE
Quick panel view font size

### ISSUE THREAD

**Issue by DavidHe1127** [dempfi/ayu#91]
Is it possible to change the file path font on quick panel view? see below

![screen shot 2017-01-22 at 10 43 07 pm](https://cloud.githubusercontent.com/assets/1167069/22182224/2cf977c2-e0f4-11e6-87a3-3a1d56c5710d.png)

I have tried setting `font.size:15` as below but it did not work.

```json
  {
    "class": "quick_panel_path_label",
    "fg": [96, 112, 128],
    "match_fg": [217, 215, 206],
    "selected_fg": [96, 112, 128],
    "selected_match_fg": [217, 215, 206],
    "font.size": 15
  },
```

Please help. Thanks in advance.

**Comment by dempfi** [comment]
I didn't find a way to control font options for quick panel :( so I couldn't change size and font family used in panel
