### ISSUE TITLE
Want the wider scroll bars (ui_wide_scrollbars) option back.

### ISSUE THREAD

**Issue by singw** [dempfi/ayu#94]
Why revert the wider scroll bars (ui_wide_scrollbars) option? It's very difficult to scroll over the side bar just using the mouse wheel when you got a very long list of opened files and project files!

REF:
https://github.com/dempfi/ayu/commit/30ca60bcc1bb0ef03748ebc53bb8548511a65060

**Comment by fnicastri** [comment]
+1

**Comment by dempfi** [comment]
hi @singw and @fnicastri, you are right and I need to fix this gap ASAP

I reverted that PR because some users experienced issues with that changes. and I need to find the cause of issues before reverting reverted PR

**Comment by dempfi** [comment]
Done in https://github.com/dempfi/ayu/releases/tag/2.2.0

**Comment by fnicastri** [comment]
Thanks!

**Comment by singw** [comment]
Thanks a lot! I can now switch to this beautiful theme!
