### ISSUE TITLE
VSCode ayu light selection + find highlight = bad contrast

### ISSUE THREAD

**Issue by isidorn** [dempfi/ayu#95]
VSCode, use ayu light theme, open find widget and search for a word, also select that word. Notice weird blend of colors

Apart from that, great theme, really enjoying it

![screen shot 2017-02-02 at 10 05 06](https://cloud.githubusercontent.com/assets/1926584/22543063/1873aa82-e92f-11e6-9b3f-879d48211268.png)

**Comment by dempfi** [comment]
hi @isidorn, I'm not maintaining VSCode version of ayu, so I can't help here :(

**Comment by isidorn** [comment]
@dempfi thanks. Where should I report this issue then?
