### ISSUE TITLE
[question]: how to let whitespace bigger?

### ISSUE THREAD

**Issue by detailyang** [dempfi/ayu#97]
Hello.

![image](https://cloud.githubusercontent.com/assets/3370345/22614973/e25027d0-eac5-11e6-892d-e053806fa7ab.png)

Now the default whitespace is so small that is very difficult to see. Not sure whether should post a issue on this repo.

Are these any way to setting? Many thanks :D

**Comment by k15a** [comment]
It's dependent on your font settings how large whitespace is. Make the font larger and the whitespace will be larger as well.

**Comment by detailyang** [comment]
@k15a gotcha thanks!
