### ISSUE TITLE
"cmd + shift + F" replace pannel is missing

### ISSUE THREAD

**Issue by sobolevn** [dempfi/ayu#99]
That's how it looks like in the default theme:
<img width="1280" alt="2017-02-26 14 02 53" src="https://cloud.githubusercontent.com/assets/4660275/23339124/6569dffe-fc2c-11e6-9b2a-12f86b695eca.png">

This how it looks like this `ayu`, as you can see 'Replace' is gone:
<img width="1280" alt="2017-02-26 14 04 27" src="https://cloud.githubusercontent.com/assets/4660275/23339134/90d1e2ea-fc2c-11e6-864d-1e7ba7bdb978.png">

I am using:
- Sublime 3
- ayu 2.2.0

Settings:

```json
{
	"color_scheme": "Packages/ayu/ayu-dark.tmTheme",
	"font_size": 15,
	"ignored_packages":
	[
		"Vintage"
	],
	"save_on_focus_lost": true,
	"theme": "ayu-dark.sublime-theme",
	"ui_big_tabs": true,
	"ui_font_size_small": false,
	"ui_separator": false
}
```

**Comment by k15a** [comment]
Try this: #12

**Comment by jrappen** [comment]
This is a Sublime Text issue.

Related: equinusocio/material-theme#67

![Drag the top edge](https://cloud.githubusercontent.com/assets/474329/8178894/a0dd09c0-1412-11e5-8ecf-f7f9ade439ae.gif)
